/**
 * 漢字の部首・構成情報
 * よく使われる漢字の成り立ちを部首と構成要素で解説
 */
interface CharInfo {
  radical: string      // 部首（ぶしゅ）
  radicalMeaning: string // 部首の意味
  components: string[]  // 構成要素
  note: string          // 由来・覚え方のヒント
}

const hanziMap: Record<string, CharInfo> = {
  // ——— あ行 ———
  '爱': { radical: '心（⺗）', radicalMeaning: 'こころ', components: ['爫', '冖', '心', '夂'], note: '心をこめて大切にする様子。下の「心」がポイント。' },
  '情': { radical: '心（忄）', radicalMeaning: 'こころ', components: ['忄', '青'], note: '心（忄）+ 青（澄んだ色）→澄んだ心＝感情。' },
  '安': { radical: '宀', radicalMeaning: 'うかんむり（家）', components: ['宀', '女'], note: '家（宀）の中に女性がいると「安心」。' },
  '全': { radical: '入', radicalMeaning: 'いる', components: ['入', '王'], note: '王（宝玉）を中に入れて完全に守る。' },
  '排': { radical: '手（扌）', radicalMeaning: 'てへん', components: ['扌', '非'], note: '手（扌）で「非（ならべる）」→並べる・手配する。' },
  '按': { radical: '手（扌）', radicalMeaning: 'てへん', components: ['扌', '安'], note: '手（扌）+ 安（安定）→手で押さえて安定させる。' },
  '照': { radical: '火（灬）', radicalMeaning: 'れっか', components: ['昭', '灬'], note: '火（灬）で明るく照らす（昭）こと。' },
  '百': { radical: '白', radicalMeaning: 'しろ', components: ['一', '白'], note: '一＋白。白は「あきらか」。百は数の多いことを表す。' },
  '分': { radical: '刀（刂）', radicalMeaning: 'かたな', components: ['八', '刀'], note: '刀で八つに分ける。上が「八」、下が「刀」。' },
  '之': { radical: '丿', radicalMeaning: 'の', components: ['丶', '乛', '乀'], note: 'もともと「行く」の意味。助詞「の」として使われる。' },
  '棒': { radical: '木', radicalMeaning: 'きへん', components: ['木', '奉'], note: '木の棒。奉は「ささげる」→まっすぐな棒。' },
  '包': { radical: '勹', radicalMeaning: 'つつみがまえ', components: ['勹', '巳'], note: '勹（つつむ）＋巳（胎児）→包み込む。' },
  '保': { radical: '人（亻）', radicalMeaning: 'にんべん', components: ['亻', '呆'], note: '人（亻）が子供（呆）を抱いて守る→保護。' },
  '护': { radical: '手（扌）', radicalMeaning: 'てへん', components: ['扌', '戸'], note: '手（扌）で戸を守る→保護する。' },
  '证': { radical: '言（讠）', radicalMeaning: 'ごんべん', components: ['讠', '正'], note: '言葉（讠）で正しいことを証明。' },
  '抱': { radical: '手（扌）', radicalMeaning: 'てへん', components: ['扌', '包'], note: '手（扌）で包み込む→抱く。' },

  // ——— か行 ———
  '感': { radical: '心', radicalMeaning: 'こころ', components: ['咸', '心'], note: '咸（みな）+ 心→心が動く＝感じる。' },
  '干': { radical: '干', radicalMeaning: 'ほす', components: ['一', '十'], note: '二本の横線と一本の縦線。もともと盾の形。' },
  '关': { radical: '八', radicalMeaning: 'はち', components: ['丷', '天'], note: '門の簡略化。閉じて関係を断つ→関わる。' },
  '系': { radical: '糸', radicalMeaning: 'いとへん', components: ['丿', '幺', '小'], note: '糸がつながる様子→系統・関係。' },
  '经': { radical: '糸（纟）', radicalMeaning: 'いとへん', components: ['纟', '圣'], note: '糸（纟）+ 縦糸。織物の縦糸→経過・経験。' },
  '验': { radical: '馬（马）', radicalMeaning: 'うまへん', components: ['马', '佥'], note: '馬（马）を調べる→検査・経験。' },
  '决': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '夬'], note: '水（氵）が流れを決める→決定。' },
  '定': { radical: '宀', radicalMeaning: 'うかんむり', components: ['宀', '正'], note: '家（宀）の中に正しいもの→安定・決定。' },
  '果': { radical: '木', radicalMeaning: 'き', components: ['田', '木'], note: '木の上に実（田）→果実・結果。' },
  '广': { radical: '广', radicalMeaning: 'まだれ', components: ['丶', '厂'], note: '広い家の屋根の形→広い。' },
  '告': { radical: '口', radicalMeaning: 'くち', components: ['牛', '口'], note: '牛の口で告げる→知らせる。' },
  '共': { radical: '八', radicalMeaning: 'はち', components: ['廿', '八'], note: '手を合わせて共有する様子→ともに。' },
  '活': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '舌'], note: '水（氵）が舌のように動く→生き生き・生活。' },
  '环': { radical: '玉（王）', radicalMeaning: 'たまへん', components: ['王', '不'], note: '玉（王）の環（わ）。一周する→環境。' },
  '境': { radical: '土', radicalMeaning: 'つちへん', components: ['土', '竟'], note: '土の境界→環境。竟は「おわり」の意。' },
  '观': { radical: '見（见）', radicalMeaning: 'みる', components: ['又', '见'], note: '手（又）をかざして見る→観察。' },
  '计': { radical: '言（讠）', radicalMeaning: 'ごんべん', components: ['讠', '十'], note: '言葉（讠）で十（多く）→計算・計画。' },
  '划': { radical: '刀（刂）', radicalMeaning: 'りっとう', components: ['戈', '刂'], note: '戈（ほこ）と刀で線を引く→計画。' },
  '交': { radical: '亠', radicalMeaning: 'なべぶた', components: ['亠', '父'], note: '足を交差させる様子→交流・交通。' },
  '通': { radical: '辶', radicalMeaning: 'しんにょう', components: ['辶', '甬'], note: '辶（道）＋甬（つきぬける）→通り抜ける。' },
  '空': { radical: '穴', radicalMeaning: 'あなかんむり', components: ['穴', '工'], note: '穴（あな）＋工（つくる）→空洞・空。' },
  '苦': { radical: '艹', radicalMeaning: 'くさかんむり', components: ['艹', '古'], note: '草（艹）のように古い→苦い・苦労。' },
  '困': { radical: '囗', radicalMeaning: 'くにがまえ', components: ['囗', '木'], note: '木が囲い（囗）の中→困難。' },

  // ——— さ行 ———
  '参': { radical: '厶', radicalMeaning: 'む', components: ['厶', '大', '彡'], note: '大＋彡（かざり）。三つの→参加。' },
  '加': { radical: '力', radicalMeaning: 'ちから', components: ['力', '口'], note: '口で力を加える→増やす。' },
  '师': { radical: '巾', radicalMeaning: 'はば', components: ['刂', '帀'], note: '軍隊（帀）→教師。教える人の意。' },
  '使': { radical: '人（亻）', radicalMeaning: 'にんべん', components: ['亻', '吏'], note: '人（亻）が吏（役人）として使う→使用。' },
  '用': { radical: '用', radicalMeaning: 'もちいる', components: ['月', '丨'], note: '月＋棒。道具を使う様子→使用。' },
  '际': { radical: '阜（阝）', radicalMeaning: 'こざとへん', components: ['阝', '示'], note: '壁（阝）の際（きわ）の示し→国際。' },
  '实': { radical: '宀', radicalMeaning: 'うかんむり', components: ['宀', '头'], note: '家（宀）に頭（かしら）→充実・実際。' },
  '质': { radical: '貝（贝）', radicalMeaning: 'かいへん', components: ['厂', '十', '贝'], note: '貝（貨幣）の品質。十（たくさん）＋厂。' },
  '视': { radical: '見（见）', radicalMeaning: 'みる', components: ['礻', '见'], note: '神（礻）のように見る→視覚。' },
  '觉': { radical: '見（见）', radicalMeaning: 'みる', components: ['学の上部', '见'], note: '学んで見る→感覚・自覚。' },
  '解': { radical: '角', radicalMeaning: 'つのへん', components: ['角', '刀', '牛'], note: '角＋刀＋牛→牛を刀で解体→理解。' },
  '绍': { radical: '糸（纟）', radicalMeaning: 'いとへん', components: ['纟', '召'], note: '糸（纟）で召す（つなぐ）→紹介。' },
  '主': { radical: '丶', radicalMeaning: 'てん', components: ['丶', '王'], note: '丶（ともしび）+ 王→主（あるじ）。中心。' },
  '义': { radical: '丶', radicalMeaning: 'てん', components: ['丶', '乂'], note: '正しいことを示す→正義・意味。' },
  '准': { radical: '冫', radicalMeaning: 'にすい', components: ['冫', '隹'], note: '氷（冫）のように水平→基準・準備。' },
  '备': { radical: '夂', radicalMeaning: 'ふゆがしら', components: ['夂', '田'], note: '田の準備をする→準備。夂は「おわる」。' },
  '除': { radical: '阜（阝）', radicalMeaning: 'こざとへん', components: ['阝', '余'], note: '壁（阝）の余りを除く→削除。' },
  '食': { radical: '食', radicalMeaning: 'しょく', components: ['人', '良'], note: '人が良きものを食べる→食事。' },
  '信': { radical: '人（亻）', radicalMeaning: 'にんべん', components: ['亻', '言'], note: '人（亻）の言葉（言）→信じる。' },
  '息': { radical: '心', radicalMeaning: 'こころ', components: ['自', '心'], note: '自分の心→いき・休息。' },
  '省': { radical: '目', radicalMeaning: 'め', components: ['少', '目'], note: '少し目をとめる→反省・省く。' },
  '相': { radical: '目', radicalMeaning: 'め', components: ['木', '目'], note: '木と目で互いを見る→相互。' },
  '续': { radical: '糸（纟）', radicalMeaning: 'いとへん', components: ['纟', '卖'], note: '糸（纟）をつなぐ→継続。' },

  // ——— た行 ———
  '大': { radical: '大', radicalMeaning: 'だい', components: ['一', '人'], note: '人が両手を広げた形→大きい。' },
  '体': { radical: '人（亻）', radicalMeaning: 'にんべん', components: ['亻', '本'], note: '人（亻）の基本（本）→身体。' },
  '谈': { radical: '言（讠）', radicalMeaning: 'ごんべん', components: ['讠', '炎'], note: '言葉（讠）で炎のように熱く→会談。' },
  '地': { radical: '土', radicalMeaning: 'つちへん', components: ['土', '也'], note: '土＋也（～である）。大地・場所。' },
  '点': { radical: '火（灬）', radicalMeaning: 'れっか', components: ['占', '灬'], note: '占う火の点→地点・点数。' },
  '电': { radical: '田', radicalMeaning: 'た', components: ['田', '乚'], note: '田＋稲妻（乚）→雷→電気。' },
  '特': { radical: '牛（牜）', radicalMeaning: 'うしへん', components: ['牜', '寺'], note: '特別な牛（牜）の寺→特別。' },

  // ——— な行 ———
  '内': { radical: '入', radicalMeaning: 'いる', components: ['冂', '入'], note: '外枠（冂）の中に入る→内部。' },
  '容': { radical: '宀', radicalMeaning: 'うかんむり', components: ['宀', '谷'], note: '家（宀）+ 谷（たに）。受け入れる→内容。' },
  '认': { radical: '言（讠）', radicalMeaning: 'ごんべん', components: ['讠', '人'], note: '言葉（讠）で人を認める→認識。' },
  '热': { radical: '火（灬）', radicalMeaning: 'れっか', components: ['执', '灬'], note: '火（灬）で執る→熱い。' },
  '闹': { radical: '門（门）', radicalMeaning: 'もんがまえ', components: ['门', '市'], note: '門の中の市（いち）→賑やか。' },

  // ——— は行 ———
  '部': { radical: '邑（阝）', radicalMeaning: 'おおざと', components: ['立', '口', '阝'], note: '立＋口＋邑。分けた区画→部分。' },
  '方': { radical: '方', radicalMeaning: 'ほう', components: ['丶', '一', '丿', '㇆'], note: '方形の旗→方向・方法。' },
  '法': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '去'], note: '水（氵）のように平らに正す→法律・方法。' },
  '别': { radical: '刀（刂）', radicalMeaning: 'りっとう', components: ['另', '刂'], note: '刀（刂）で「另」を分ける→区別。' },
  '变': { radical: '又', radicalMeaning: 'また', components: ['亦', '又'], note: '亦（また）＋又（さらに）→変化。' },
  '表': { radical: '衣', radicalMeaning: 'ころも', components: ['青の上部', '衣の下部'], note: '衣の表面→表示・表現。' },
  '品': { radical: '口', radicalMeaning: 'くち', components: ['口', '口', '口'], note: '三つの口→品物。多くの口で評価する。' },
  '复': { radical: '夊', radicalMeaning: 'すいにょう', components: ['ノ', '日', '夊'], note: '日が繰り返し出る→復習。' },
  '习': { radical: '乙', radicalMeaning: 'おつ', components: ['羽の片方', '白'], note: '羽ばたく→練習を重ねる→学習。' },
  '富': { radical: '宀', radicalMeaning: 'うかんむり', components: ['宀', '畐'], note: '家（宀）に畐（みちる）→豊富。' },

  // ——— ま行 ———
  '忙': { radical: '心（忄）', radicalMeaning: 'りっしんべん', components: ['忄', '亡'], note: '心（忄）が亡くなるほど→忙しい。' },
  '明': { radical: '日', radicalMeaning: 'ひへん', components: ['日', '月'], note: '日＋月→明るい・明日。太陽と月が輝く。' },
  '无': { radical: '无', radicalMeaning: 'む', components: ['一', '尢'], note: '一＋ナ（人が曲がる）→無。' },
  '目': { radical: '目', radicalMeaning: 'め', components: ['口', '二'], note: '目の形をかたどった象形文字。' },
  '问': { radical: '口', radicalMeaning: 'くち', components: ['门', '口'], note: '門の口→質問する。' },
  '题': { radical: '頁（页）', radicalMeaning: 'おおがい', components: ['是', '页'], note: '是（これ）＋頁（頭）→問題の題。' },

  // ——— や行 ———
  '要': { radical: '襾', radicalMeaning: 'にし', components: ['襾', '女'], note: '西（襾）＋女→腰に手を当てる→重要・必要。' },
  '友': { radical: '又', radicalMeaning: 'また', components: ['ナ', '又'], note: '手（ナ）と手（又）→助け合う→友達。' },
  '有': { radical: '月', radicalMeaning: 'つきへん', components: ['ナ', '月'], note: '手（ナ）に月（肉）を持つ→所有する。' },
  '以': { radical: '人', radicalMeaning: 'ひと', components: ['厶', '人'], note: '人＋厶（よる）。〜をもって→以前・以後。' },
  '注': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '主'], note: '水（氵）を主に注ぐ→注意。' },
  '意': { radical: '心', radicalMeaning: 'こころ', components: ['立', '日', '心'], note: '心に立つ日の意→意味・意見。' },
  '约': { radical: '糸（纟）', radicalMeaning: 'いとへん', components: ['纟', '勺'], note: '糸（纟）でしばる→約束。' },
  '预': { radical: '頁（页）', radicalMeaning: 'おおがい', components: ['予', '页'], note: '予（あらかじめ）＋頁（頭）→予習・予定。' },
  '愿': { radical: '心', radicalMeaning: 'こころ', components: ['原', '心'], note: '原＋心→心の原点＝願い。' },

  // ——— ら行 ———
  '拉': { radical: '手（扌）', radicalMeaning: 'てへん', components: ['扌', '立'], note: '手（扌）で立たせる→引っ張る。' },
  '理': { radical: '玉（王）', radicalMeaning: 'たまへん', components: ['王', '里'], note: '玉（王）の筋目（里）→整理・理由。' },
  '利': { radical: '刀（刂）', radicalMeaning: 'りっとう', components: ['禾', '刂'], note: '禾（穀物）＋刀→鋭く切る→利益。' },
  '力': { radical: '力', radicalMeaning: 'ちから', components: ['腕の形'], note: '腕の筋肉を表す象形文字→ちから。' },
  '联': { radical: '耳', radicalMeaning: 'みみへん', components: ['耳', '关'], note: '耳を関わらせる→連絡・関連。' },
  '练': { radical: '糸（纟）', radicalMeaning: 'いとへん', components: ['纟', '东の旧字'], note: '糸（纟）をより合わせる→練習。' },
  '林': { radical: '木', radicalMeaning: 'きへん', components: ['木', '木'], note: '木が二つ→林。たくさんの木。' },
  '零': { radical: '雨', radicalMeaning: 'あめかんむり', components: ['雨', '令'], note: '雨（あめ）＋令（しずく）→零（ゼロ）。' },
  '例': { radical: '人（亻）', radicalMeaning: 'にんべん', components: ['亻', '列'], note: '人（亻）の列→例・例えば。' },
  '旅': { radical: '方', radicalMeaning: 'ほうへん', components: ['方', '⺉', '𠂡'], note: '旗（方）を掲げて行く→旅行。' },
  '礼': { radical: '示（礻）', radicalMeaning: 'しめすへん', components: ['礻', '乚'], note: '神（礻）への曲がった（乚）→礼儀。' },
  '谅': { radical: '言（讠）', radicalMeaning: 'ごんべん', components: ['讠', '京'], note: '言葉（讠）で京（高く）→寛大→許す。' },

  // ——— わ行 ———
  '忘': { radical: '心', radicalMeaning: 'こころ', components: ['亡', '心'], note: '心が亡くなる→忘れる。' },
  '味': { radical: '口', radicalMeaning: 'くちへん', components: ['口', '未'], note: '口で未（まだ）味わう→味。' },

  // —— HSK4 頻出の追加漢字 ——
  '价': { radical: '人（亻）', radicalMeaning: 'にんべん', components: ['亻', '介'], note: '人（亻）＋介（間に入る）→価値。人が介在して価値が決まる。' },
  '值': { radical: '人（亻）', radicalMeaning: 'にんべん', components: ['亻', '直'], note: '人（亻）＋直（まっすぐ）→値打ち。' },
  '科': { radical: '禾', radicalMeaning: 'のぎへん', components: ['禾', '斗'], note: '禾（穀物）＋斗（ます）→分けて測る→科学。' },
  '技': { radical: '手（扌）', radicalMeaning: 'てへん', components: ['扌', '支'], note: '手（扌）＋支（ささえる）→技術。' },
  '段': { radical: '殳', radicalMeaning: 'るまた', components: ['丨', '一', '殳'], note: '段階を表す。工具で切る様子→段階。' },
  '况': { radical: '冫', radicalMeaning: 'にすい', components: ['冫', '兄'], note: '氷（冫）のように冷たい状態→状況。' },
  '汉': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '又'], note: '水（氵）＋又（手）。漢の略→漢字。' },
  '字': { radical: '子', radicalMeaning: 'こへん', components: ['宀', '子'], note: '家（宀）で子が字を学ぶ→文字。' },
  '教': { radical: '攵', radicalMeaning: 'のぶん', components: ['孝', '攵'], note: '孝＋攵（教える手）→教育。' },
  '育': { radical: '肉（月）', radicalMeaning: 'にくづき', components: ['云', '月'], note: '云（うまれる）＋肉（月）→育てる。' },
  '室': { radical: '宀', radicalMeaning: 'うかんむり', components: ['宀', '至'], note: '家（宀）＋至（いたる）→部屋・教室。' },
  '堂': { radical: '土', radicalMeaning: 'つち', components: ['尚', '土'], note: '高い土の上→堂（広間）。' },
  '始': { radical: '女', radicalMeaning: 'おんなへん', components: ['女', '台'], note: '女＋台（はじまり）→開始。' },
  '春': { radical: '日', radicalMeaning: 'ひ', components: ['𡗷', '日'], note: '日が暖かくなる→春。三＋人＋日。' },
  '夏': { radical: '夊', radicalMeaning: 'すいにょう', components: ['頁の省略形', '夊'], note: '頁（おおがい）＋夊。暑い季節→夏。' },
  '秋': { radical: '禾', radicalMeaning: 'のぎへん', components: ['禾', '火'], note: '禾（穀物）＋火（紅葉）→秋。' },
  '冬': { radical: '冫', radicalMeaning: 'にすい', components: ['夂', '冫'], note: '夂（おわる）＋冫（氷）→冬。' },
  '星': { radical: '日', radicalMeaning: 'ひへん', components: ['日', '生'], note: '日＋生（うまれる）＝星。' },
  '期': { radical: '月', radicalMeaning: 'つきへん', components: ['其', '月'], note: '其＋月→期間・学期。月で時を数える。' },
  '假': { radical: '人（亻）', radicalMeaning: 'にんべん', components: ['亻', '叚'], note: '人（亻）が借りる（叚）→休暇・仮。' },
  '票': { radical: '示', radicalMeaning: 'しめす', components: ['西', '示'], note: '西＋示（しめす）→切符・投票。' },
  '漂': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '票'], note: '水（氵）＋票→水に漂う→綺麗。' },
  '简': { radical: '竹（⺮）', radicalMeaning: 'たけかんむり', components: ['⺮', '间'], note: '竹（⺮）＋間→竹簡→簡単。' },
  '单': { radical: '十', radicalMeaning: 'じゅう', components: ['丷', '田', '十'], note: '一つの田→単位・簡単。' },
  '第': { radical: '竹（⺮）', radicalMeaning: 'たけかんむり', components: ['⺮', '弟'], note: '竹簡（⺮）の順序（弟）→第〜。' },
  '页': { radical: '頁（页）', radicalMeaning: 'おおがい', components: ['一', '丿', '贝'], note: '頭（頁）→ページ。' },
  '篇': { radical: '竹（⺮）', radicalMeaning: 'たけかんむり', components: ['⺮', '扁'], note: '竹簡（⺮）＋扁→文章の一篇。' },
  '写': { radical: '宀', radicalMeaning: 'うかんむり', components: ['宀', '写'], note: '家（宀）で書き写す→書く。' },
  '读': { radical: '言（讠）', radicalMeaning: 'ごんべん', components: ['讠', '卖'], note: '言葉（讠）を売（ひらく）→読む。' },
  '记': { radical: '言（讠）', radicalMeaning: 'ごんべん', components: ['讠', '己'], note: '言葉（讠）を己に→記憶。' },
  '得': { radical: '彳', radicalMeaning: 'ぎょうにんべん', components: ['彳', '㝵'], note: '彳（行く）＋得る→獲得。' },
  '懂': { radical: '心（忄）', radicalMeaning: 'りっしんべん', components: ['忄', '董'], note: '心（忄）＋董（ととのえる）→理解。' },
  '答': { radical: '竹（⺮）', radicalMeaning: 'たけかんむり', components: ['⺮', '合'], note: '竹（⺮）を合わせて答える→回答。' },
  '笑': { radical: '竹（⺮）', radicalMeaning: 'たけかんむり', components: ['⺮', '夭'], note: '竹（⺮）＋夭（わかい）→笑顔。' },
  '哭': { radical: '口', radicalMeaning: 'くち', components: ['吅', '犬'], note: '二つの口＋犬→泣く。' },
  '流': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '㐬'], note: '水（氵）＋流れる→流行。' },
  '海': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '毎'], note: '水（氵）＋毎→広い海。' },
  '河': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '可'], note: '水（氵）＋可→大河。' },
  '湖': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '胡'], note: '水（氵）＋胡→湖。' },
  '清': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '青'], note: '水（氵）＋青→清らか。' },
  '深': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '罙'], note: '水（氵）＋深さ→深い。' },
  '温': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '昷'], note: '水（氵）＋昷（あたたかい）→温度。' },
  '坚': { radical: '土', radicalMeaning: 'つち', components: ['収', '土'], note: '土を固める→堅い。' },
  '持': { radical: '手（扌）', radicalMeaning: 'てへん', components: ['扌', '寺'], note: '手（扌）＋寺→持つ→維持。' },
  '赢': { radical: '貝（贝）', radicalMeaning: 'かい', components: ['亡', '口', '月', '贝', '凡'], note: '貝（お金）を得る→勝つ。' },
  '输': { radical: '車（车）', radicalMeaning: 'くるまへん', components: ['车', '俞'], note: '車（车）で運ぶ→輸送→負ける。' },
  '赛': { radical: '貝（贝）', radicalMeaning: 'かい', components: ['宀', '井', '一', '贝'], note: '貝（賞品）を競う→試合。' },
  '篮': { radical: '竹（⺮）', radicalMeaning: 'たけかんむり', components: ['⺮', '监'], note: '竹かご→バスケット→篮球（バスケ）。' },
  '球': { radical: '玉（王）', radicalMeaning: 'たまへん', components: ['王', '求'], note: '玉（王）＋求→球形→ボール。' },
  '场': { radical: '土', radicalMeaning: 'つちへん', components: ['土', '昜の略'], note: '土＋昜→広場・場所。' },
  '健': { radical: '人（亻）', radicalMeaning: 'にんべん', components: ['亻', '建'], note: '人（亻）＋建（たつ）→健康。' },
  '康': { radical: '广', radicalMeaning: 'まだれ', components: ['广', '隶'], note: '广（広い）＋隶→安らか→健康。' },
  '休': { radical: '人（亻）', radicalMeaning: 'にんべん', components: ['亻', '木'], note: '人（亻）が木のそばで休む→休息。' },
  '睡': { radical: '目', radicalMeaning: 'めへん', components: ['目', '垂'], note: '目＋垂（たれる）→眠る。' },
  '醒': { radical: '酉', radicalMeaning: 'とりへん', components: ['酉', '星'], note: '酒（酉）から星のように→目覚める。' },
  '舒': { radical: '舌', radicalMeaning: 'した', components: ['舍', '予'], note: '舌をゆるめる→気持ちいい→快適。' },
  '适': { radical: '辶', radicalMeaning: 'しんにょう', components: ['辶', '舌'], note: '舌（した）＋道（辶）→舌に合う→適切。' },
  '医': { radical: '匚', radicalMeaning: 'はこがまえ', components: ['匚', '矢'], note: '箱（匚）の中の矢→治療→医者。' },
  '药': { radical: '艹', radicalMeaning: 'くさかんむり', components: ['艹', '约'], note: '草（艹）＋約→薬草→薬。' },
  '顾': { radical: '頁（页）', radicalMeaning: 'おおがい', components: ['厄', '页'], note: '頭（页）を回らす→顧客・回顧。' },
  '客': { radical: '宀', radicalMeaning: 'うかんむり', components: ['宀', '各'], note: '家（宀）に来る各人→お客。' },
  '诉': { radical: '言（讠）', radicalMeaning: 'ごんべん', components: ['讠', '斥'], note: '言葉（讠）で訴える→告訴。' },
  '乱': { radical: '乙', radicalMeaning: 'おつ', components: ['舌', '乚'], note: '舌が曲がる→混乱。' },
  '杂': { radical: '木', radicalMeaning: 'き', components: ['九', '木'], note: '九つの木→雑多。' },
  '志': { radical: '心', radicalMeaning: 'こころ', components: ['士', '心'], note: '士の心→志（こころざし）。' },
  '赶': { radical: '走', radicalMeaning: 'そうにょう', components: ['走', '干'], note: '走って追いかける→急ぐ。' },
  '趣': { radical: '走', radicalMeaning: 'そうにょう', components: ['走', '取'], note: '走って取る→趣向・興味。' },
  '跟': { radical: '足（⻊）', radicalMeaning: 'あしへん', components: ['⻊', '艮'], note: '足（⻊）＋艮（とどまる）→ついていく。' },
  '路': { radical: '足（⻊）', radicalMeaning: 'あしへん', components: ['⻊', '各'], note: '足（⻊）＋各→道・道路。' },
  '踢': { radical: '足（⻊）', radicalMeaning: 'あしへん', components: ['⻊', '易'], note: '足（⻊）で易（かわる）→蹴る。' },
  '满': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '㒼'], note: '水（氵）が溢れる→満足。' },
  '低': { radical: '人（亻）', radicalMeaning: 'にんべん', components: ['亻', '氐'], note: '人が低く頭を下げる→低い。' },
  '高': { radical: '高', radicalMeaning: 'たかい', components: ['亠', '口', '冂', '口'], note: '高い建物の形。台の上に高い楼閣。' },
  '校': { radical: '木', radicalMeaning: 'きへん', components: ['木', '交'], note: '木＋交→学校（木造校舎の意）。' },
  '园': { radical: '囗', radicalMeaning: 'くにがまえ', components: ['囗', '元'], note: '囲い（囗）＋元→庭園・公園。' },
  '站': { radical: '立', radicalMeaning: 'たつへん', components: ['立', '占'], note: '立って場所を占める→駅・立つ。' },
  '租': { radical: '禾', radicalMeaning: 'のぎへん', components: ['禾', '且'], note: '禾（穀物の税）＋且→租税→賃貸。' },
  '饺': { radical: '食（饣）', radicalMeaning: 'しょくへん', components: ['饣', '交'], note: '食（饣）＋交→交ぜて包む→餃子。' },
  '烧': { radical: '火', radicalMeaning: 'ひへん', components: ['火', '尧'], note: '火＋尧（高い）→焼く。' },
  '汤': { radical: '水（氵）', radicalMeaning: 'さんずい', components: ['氵', '昜'], note: '水（氵）＋昜（あたたかい）→スープ。' },
  '碗': { radical: '石', radicalMeaning: 'いしへん', components: ['石', '宛'], note: '石＋宛→茶碗。' },
  '筷': { radical: '竹（⺮）', radicalMeaning: 'たけかんむり', components: ['⺮', '快'], note: '竹＋快→箸（はし）。' },
  '盘': { radical: '皿', radicalMeaning: 'さら', components: ['舟', '皿'], note: '舟形の皿→お盆・お皿。' },
  '瓶': { radical: '瓦', radicalMeaning: 'かわら', components: ['并', '瓦'], note: '并（あわせる）＋瓦（かわら）→瓶。' },
  '杯': { radical: '木', radicalMeaning: 'きへん', components: ['木', '不'], note: '木の器（不）→コップ。' },
  '啤': { radical: '口', radicalMeaning: 'くちへん', components: ['口', '卑'], note: '口＋卑→ビール（音訳）。' },
  '耳': { radical: '耳', radicalMeaning: 'みみ', components: ['耳の形'], note: '耳の形をかたどった象形文字。' },
  '闻': { radical: '門（门）', radicalMeaning: 'もんがまえ', components: ['门', '耳'], note: '門の耳→聞く。門の外の音を耳で聞く。' },
  '死': { radical: '歹', radicalMeaning: 'かばねへん', components: ['歹', '匕'], note: '歹（かばね）＋匕→死ぬ。' },
  '考': { radical: '老', radicalMeaning: 'おいかんむり', components: ['耂', '丂'], note: '老＋丂→考える・試験。' },
  '试': { radical: '言（讠）', radicalMeaning: 'ごんべん', components: ['讠', '式'], note: '言葉（讠）＋式→試験。' },
  '蛋': { radical: '虫', radicalMeaning: 'むしへん', components: ['疋', '虫'], note: '疋＋虫→卵。' },
  '糕': { radical: '米', radicalMeaning: 'こめへん', components: ['米', '羔'], note: '米＋羔→お菓子・ケーキ。' },
  '糖': { radical: '米', radicalMeaning: 'こめへん', components: ['米', '唐'], note: '米＋唐→砂糖。' },
  '盐': { radical: '皿', radicalMeaning: 'さら', components: ['土', '卜', '皿'], note: '土＋卜＋皿→塩。' },
  '酸': { radical: '酉', radicalMeaning: 'とりへん', components: ['酉', '夋'], note: '酒（酉）のように酸っぱい→酸。' },
  '辛': { radical: '辛', radicalMeaning: 'からい', components: ['立', '十'], note: '立＋十。刃物で切る→辛い。' },
  '辣': { radical: '辛', radicalMeaning: 'からい', components: ['辛', '束の略'], note: '辛＋束→辛い。' },
}

/**
 * 漢字の分解情報を取得
 */
export function getCharInfo(char: string): CharInfo | null {
  return hanziMap[char] ?? null
}

/**
 * 単語を1文字ずつ分解して情報を返す
 */
export function breakdownWord(hanzi: string): { char: string; info: CharInfo | null }[] {
  return [...hanzi].map(char => ({
    char,
    info: getCharInfo(char),
  }))
}
