/**
 * HSK4 データ生成スクリプト
 * 1. 不足している漢字構成情報を生成
 * 2. 不足している語源・覚え方（mnemonic）を生成
 */
const fs = require('fs');
const path = require('path');

// ── 残りの漢字構成データ ──
const remainingHanzi = {
  "(": { radical: "(", radicalMeaning: "かっこ", components: ["("], note: "左括弧。" },
  ")": { radical: ")", radicalMeaning: "かっこ", components: [")"], note: "右括弧。" },
  "…": { radical: "…", radicalMeaning: "てんてん", components: ["…"], note: "省略記号。" },
  "丈": { radical: "一", radicalMeaning: "いち", components: ["丈"], note: "長さ単位（約3.3m）。日本語の漢字「丈（ジョウ・たけ）」と同じ。" },
  "与": { radical: "一", radicalMeaning: "いち", components: ["与"], note: "與の簡体字→〜と。日本語の漢字「与（ヨ・あたえる）」と同じ。" },
  "专": { radical: "一", radicalMeaning: "いち", components: ["专"], note: "専の簡体字→専門。日本語の漢字「専（セン）」の簡体字。" },
  "且": { radical: "一", radicalMeaning: "いち", components: ["且"], note: "かつ・その上。日本語の漢字「且（ショ・かつ）」と同じ。" },
  "世": { radical: "一", radicalMeaning: "いち", components: ["世"], note: "三十年→一世代→世界。日本語の漢字「世（セイ・よ）」と同じ。" },
  "业": { radical: "一", radicalMeaning: "いち", components: ["业"], note: "業の簡体字→事業。日本語の漢字「業（ギョウ）」の簡体字。" },
  "两": { radical: "一", radicalMeaning: "いち", components: ["两"], note: "二つの→両。日本語の漢字「両（リョウ）」の簡体字。" },
  "严": { radical: "一", radicalMeaning: "いち", components: ["严"], note: "嚴の簡体字→厳しい。日本語の漢字「厳（ゲン）」の簡体字。" },
  "个": { radical: "人", radicalMeaning: "ひと", components: ["个"], note: "箇の簡体字→量詞（一つ二つ）。日本語の漢字「個（コ）」の簡体字。" },
  "中": { radical: "丨", radicalMeaning: "たてぼう", components: ["口", "丨"], note: "口＋丨→中。日本語の漢字「中（チュウ・なか）」と同じ。" },
  "丰": { radical: "丨", radicalMeaning: "たてぼう", components: ["丰"], note: "豐の簡体字→豊か。日本語の漢字「豊（ホウ）」の簡体字。" },
  "丽": { radical: "一", radicalMeaning: "いち", components: ["丽"], note: "麗の簡体字→美しい。日本語の漢字「麗（レイ）」の簡体字。" },
  "久": { radical: "丿", radicalMeaning: "の", components: ["久"], note: "長く→久しい。日本語の漢字「久（キュウ・ひさしい）」と同じ。" },
  "乎": { radical: "丿", radicalMeaning: "の", components: ["乎"], note: "〜か。文語疑問。日本語の漢字「乎（コ）」と同じ。" },
  "乐": { radical: "丿", radicalMeaning: "の", components: ["乐"], note: "樂の簡体字→音楽·楽しい。日本語の漢字「楽（ガク）」の簡体字。" },
  "乒": { radical: "丿", radicalMeaning: "の", components: ["乒"], note: "卓球の擬音。「乒乓」でピンポン。" },
  "乓": { radical: "丿", radicalMeaning: "の", components: ["乓"], note: "卓球の擬音。卓球＝乒乓球。" },
  "乘": { radical: "丿", radicalMeaning: "の", components: ["乘"], note: "乗る。日本語の漢字「乗（ジョウ）」の旧字体。" },
  "也": { radical: "乙", radicalMeaning: "おつ", components: ["也"], note: "〜もまた。日本語の漢字「也（ヤ・なり）」と同じ。" },
  "书": { radical: "乙", radicalMeaning: "おつ", components: ["书"], note: "書の簡体字→本·書く。日本語の漢字「書（ショ）」の簡体字。" },
  "争": { radical: "刀（⺈）", radicalMeaning: "かたな", components: ["⺈", "彐", "亅"], note: "争う。日本語の漢字「争（ソウ・あらそう）」と同じ。" },
  "事": { radical: "亅", radicalMeaning: "はねぼう", components: ["事"], note: "こと·仕事。日本語の漢字「事（ジ・こと）」と同じ。" },
  "于": { radical: "一", radicalMeaning: "いち", components: ["于"], note: "〜において·〜に。日本語の漢字「于（ウ）」と同じ。" },
  "云": { radical: "一", radicalMeaning: "いち", components: ["云"], note: "雲の略→言う。日本語の漢字「云（ウン・いう）」と同じ。" },
  "互": { radical: "二", radicalMeaning: "に", components: ["互"], note: "互い。日本語の漢字「互（ゴ・たがい）」と同じ。" },
  "亚": { radical: "一", radicalMeaning: "いち", components: ["亚"], note: "亞の簡体字→アジア·次。日本語の漢字「亜（ア）」の簡体字。" },
  "些": { radical: "二", radicalMeaning: "に", components: ["此", "二"], note: "此＋二→いくつか。「一些」で少し。" },
  "京": { radical: "亠", radicalMeaning: "なべぶた", components: ["京"], note: "都·北京。日本語の漢字「京（キョウ）」と同じ。" },
  "仅": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "又"], note: "僅の簡体字→わずか。日本語の漢字「僅（キン）」の簡体字。" },
  "介": { radical: "人", radicalMeaning: "ひと", components: ["人", "八"], note: "間に入る→紹介。日本語の漢字「介（カイ）」と同じ。" },
  "仍": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "乃"], note: "なお·やはり。日本語の漢字「仍（ジョウ）」と同じ。" },
  "仔": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "子"], note: "小さい。日本語の漢字「仔（シ）」と同じ。" },
  "付": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "寸"], note: "付ける·支払う。日本語の漢字「付（フ・つける）」と同じ。" },
  "代": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "弋"], note: "代わる。日本語の漢字「代（ダイ・かわる）」と同じ。" },
  "任": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "王"], note: "任せる·任務。「任何」でどんな〜でも。" },
  "份": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "分"], note: "分け前→部分·量詞。日本語の漢字「份（フン）」に相当。" },
  "众": { radical: "人", radicalMeaning: "ひと", components: ["人", "从", "人"], note: "衆の簡体字→大衆。三人で多い。" },
  "优": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "尤"], note: "優の簡体字→優れる。日本語の漢字「優（ユウ）」の簡体字。" },
  "伙": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "火"], note: "仲間。「家伙」で道具·奴。" },
  "会": { radical: "人", radicalMeaning: "ひと", components: ["会"], note: "會の簡体字→会う·できる。" },
  "伞": { radical: "人", radicalMeaning: "ひと", components: ["伞"], note: "傘の簡体字→傘。日本語の漢字「傘（サン）」の簡体字。" },
  "传": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "专"], note: "傳の簡体字→伝える。日本語の漢字「伝（デン）」の簡体字だが簡体は「传」。" },
  "伤": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "伤の略"], note: "傷の簡体字→傷·怪我。日本語の漢字「傷（ショウ）」の簡体字。" },
  "估": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "古"], note: "見積もる。日本語の漢字「估（コ）」に相当。" },
  "位": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "立"], note: "位置·位。日本語の漢字「位（イ・くらい）」と同じ。" },
  "住": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "主"], note: "住む。日本語の漢字「住（ジュウ・すむ）」と同じ。" },
  "供": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "共"], note: "供える·提供。日本語の漢字「供（キョウ・そなえる）」と同じ。" },
  "便": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "更"], note: "便利·〜するとすぐ。日本語の漢字「便（ベン）」と同じ。" },
  "俩": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "两"], note: "二人（口語）。日本語の漢字「倆（リョウ）」の簡体字。" },
  "修": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "攸", "彡"], note: "修める。日本語の漢字「修（シュウ・おさめる）」と同じ。" },
  "倍": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "咅"], note: "倍。日本語の漢字「倍（バイ）」と同じ。" },
  "倒": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "到"], note: "倒れる·逆さ。日本語の漢字「倒（トウ・たおれる）」と同じ。" },
  "借": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "昔"], note: "借りる。日本語の漢字「借（シャク・かりる）」と同じ。" },
  "停": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "亭"], note: "止まる。日本語の漢字「停（テイ・とまる）」と同じ。" },
  "偶": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "禺"], note: "偶々→偶然。日本語の漢字「偶（グウ）」と同じ。" },
  "傅": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "尃"], note: "師匠·指導者。日本語の漢字「傅（フ）」と同じ。" },
  "傲": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "敖"], note: "傲る→傲慢。日本語の漢字「傲（ゴウ）」と同じ。" },
  "像": { radical: "人（亻）", radicalMeaning: "にんべん", components: ["亻", "象"], note: "像·〜のような。日本語の漢字「像（ゾウ）」と同じ。" },
  "允": { radical: "儿", radicalMeaning: "にんにょう", components: ["厶", "儿"], note: "許す。日本語の漢字「允（イン・ゆるす）」と同じ。" },
  "元": { radical: "儿", radicalMeaning: "にんにょう", components: ["二", "儿"], note: "元·お金の単位。日本語の漢字「元（ゲン・もと）」と同じ。" },
  "光": { radical: "儿", radicalMeaning: "にんにょう", components: ["光"], note: "光る。日本語の漢字「光（コウ・ひかる）」と同じ。" },
  "克": { radical: "儿", radicalMeaning: "にんにょう", components: ["十", "口", "儿"], note: "克つ·グラム。日本語の漢字「克（コク・かつ）」と同じ。" },
  "免": { radical: "儿", radicalMeaning: "にんにょう", components: ["免"], note: "免れる·免除。日本語の漢字「免（メン・まぬかれる）」と同じ。" },
  "兴": { radical: "八", radicalMeaning: "はち", components: ["兴"], note: "興の簡体字→興味·盛ん。日本語の漢字「興（コウ）」の簡体字。" },
  "其": { radical: "八", radicalMeaning: "はち", components: ["其"], note: "その。日本語の漢字「其（キ・その）」と同じ。" },
  "具": { radical: "八", radicalMeaning: "はち", components: ["具"], note: "具える→道具。日本語の漢字「具（グ・そなえる）」と同じ。" },
  "典": { radical: "八", radicalMeaning: "はち", components: ["典"], note: "書物→字典。日本語の漢字「典（テン）」と同じ。" },
  "养": { radical: "八", radicalMeaning: "はち", components: ["养"], note: "養の簡体字→養う。日本語の漢字「養（ヨウ）」の簡体字。" },
  "再": { radical: "冂", radicalMeaning: "けいがまえ", components: ["再"], note: "再び。日本語の漢字「再（サイ・ふたたび）」と同じ。" },
  "冒": { radical: "冂", radicalMeaning: "けいがまえ", components: ["冃", "目"], note: "冒す→危険を冒す。日本語の漢字「冒（ボウ・おかす）」と同じ。" },
  "勇": { radical: "力", radicalMeaning: "ちから", components: ["甬", "力"], note: "勇ましい。日本語の漢字「勇（ユウ・いさましい）」と同じ。" },
  "勺": { radical: "勹", radicalMeaning: "つつみがまえ", components: ["勺"], note: "しゃくし·さじ。日本語の漢字「勺（シャク）」と同じ。" },
  "匙": { radical: "匕", radicalMeaning: "さじ", components: ["是", "匕"], note: "さじ·スプーン。「钥匙」で鍵。" },
  "区": { radical: "匚", radicalMeaning: "はこがまえ", components: ["匚", "乂"], note: "區の簡体字→区域。日本語の漢字「区（ク）」と同じ。" },
  "午": { radical: "十", radicalMeaning: "じゅう", components: ["午"], note: "午前·午後。日本語の漢字「午（ゴ）」と同じ。" },
  "半": { radical: "十", radicalMeaning: "じゅう", components: ["半"], note: "半分。日本語の漢字「半（ハン・なかば）」と同じ。" },
  "博": { radical: "十", radicalMeaning: "じゅう", components: ["十", "尃"], note: "博す→博士·博覧。日本語の漢字「博（ハク）」と同じ。" },
  "占": { radical: "卜", radicalMeaning: "うらなう", components: ["卜", "口"], note: "占める·占う。日本語の漢字「占（セン・しめる）」と同じ。" },
  "卡": { radical: "卜", radicalMeaning: "うらなう", components: ["上", "下"], note: "カード·詰まる。日本語の漢字「卡（カ）」に相当。" },
  "卫": { radical: "卩", radicalMeaning: "わりふ", components: ["卫"], note: "衛の簡体字→守る·衛生。日本語の漢字「衛（エイ）」の簡体字。" },
  "印": { radical: "卩", radicalMeaning: "わりふ", components: ["印"], note: "印·印刷。日本語の漢字「印（イン・しるし）」と同じ。" },
  "危": { radical: "卩", radicalMeaning: "わりふ", components: ["危"], note: "危ない。日本語の漢字「危（キ・あぶない）」と同じ。" },
  "即": { radical: "卩", radicalMeaning: "わりふ", components: ["即"], note: "即ち。日本語の漢字「即（ソク・すなわち）」と同じ。" },
  "却": { radical: "卩", radicalMeaning: "わりふ", components: ["去", "卩"], note: "しかし·退く。日本語の漢字「却（キャク）」と同じ。" },
  "历": { radical: "厂", radicalMeaning: "がんだれ", components: ["厂", "力"], note: "歴の簡体字→歴史·カレンダー。日本語の漢字「歴（レキ）」の簡体字。" },
  "厉": { radical: "厂", radicalMeaning: "がんだれ", components: ["厂", "万"], note: "厲の簡体字→厳しい·激しい。日本語の漢字「厲（レイ）」の簡体字。" },
  "压": { radical: "厂", radicalMeaning: "がんだれ", components: ["厂", "土", "丶"], note: "壓の簡体字→押す·圧力。日本語の漢字「圧（アツ）」の簡体字·压。" },
  "厌": { radical: "厂", radicalMeaning: "がんだれ", components: ["厂", "犬"], note: "厭の簡体字→嫌う。日本語の漢字「厭（エン）」の簡体字。" },
  "厚": { radical: "厂", radicalMeaning: "がんだれ", components: ["厂", "日", "子"], note: "厚い。日本語の漢字「厚（コウ・あつい）」と同じ。" },
  "又": { radical: "又", radicalMeaning: "また", components: ["又"], note: "また·さらに。日本語の漢字「又（ユウ・また）」と同じ。" },
  "及": { radical: "又", radicalMeaning: "また", components: ["及"], note: "及ぶ。日本語の漢字「及（キュウ・およぶ）」と同じ。" },
  "双": { radical: "又", radicalMeaning: "また", components: ["又", "又"], note: "雙の簡体字→二つ·ペア。日本語の漢字「双（ソウ）」と同じ。" },
  "叔": { radical: "又", radicalMeaning: "また", components: ["上", "小", "又"], note: "おじ。日本語の漢字「叔（シュク・おじ）」と同じ。" },
  "哪": { radical: "口", radicalMeaning: "くちへん", components: ["口", "那"], note: "どれ·どこ。疑問詞。" },
  "圾": { radical: "土", radicalMeaning: "つちへん", components: ["土", "及"], note: "垃圾（lājī）＝ゴミ。" },
  "址": { radical: "土", radicalMeaning: "つちへん", components: ["土", "止"], note: "地址＝住所。日本語の漢字「址（シ）」と同じ。" },
  "块": { radical: "土", radicalMeaning: "つちへん", components: ["土", "夬"], note: "塊の簡体字→かたまり·量詞。日本語の漢字「塊（カイ）」の簡体字。" },
  "垃": { radical: "土", radicalMeaning: "つちへん", components: ["土", "立"], note: "垃圾＝ゴミ。" },
  "基": { radical: "土", radicalMeaning: "つち", components: ["其", "土"], note: "基本·基礎。日本語の漢字「基（キ・もと）」と同じ。" },
  "堵": { radical: "土", radicalMeaning: "つちへん", components: ["土", "者"], note: "塞ぐ·詰まる。日本語の漢字「堵（ト）」に相当。" },
  "塑": { radical: "土", radicalMeaning: "つち", components: ["朔", "土"], note: "塑像·プラスチック。日本語の漢字「塑（ソ）」と同じ。" },
  "填": { radical: "土", radicalMeaning: "つちへん", components: ["土", "真"], note: "埋める·記入。日本語の漢字「填（テン）」と同じ。" },
  "增": { radical: "土", radicalMeaning: "つちへん", components: ["土", "曾"], note: "増やす。日本語の漢字「増（ゾウ）」の簡体字。" },
  "士": { radical: "士", radicalMeaning: "さむらい", components: ["士"], note: "武士·人士。日本語の漢字「士（シ）」と同じ。" },
  "处": { radical: "夂", radicalMeaning: "ふゆがしら", components: ["夂", "卜"], note: "處の簡体字→場所·処理。日本語の漢字「処（ショ）」の簡体字に類似。" },
  "太": { radical: "大", radicalMeaning: "だい", components: ["大", "丶"], note: "太い·〜すぎる。「太太」で奥さん。日本語の漢字「太（タイ・ふとい）」と同じ。" },
  "失": { radical: "大", radicalMeaning: "だい", components: ["失"], note: "失う。日本語の漢字「失（シツ・うしなう）」と同じ。" },
  "奇": { radical: "大", radicalMeaning: "だい", components: ["大", "可"], note: "奇妙→珍しい。日本語の漢字「奇（キ・めずらしい）」と同じ。" },
  "奋": { radical: "大", radicalMeaning: "だい", components: ["大", "田"], note: "奮の簡体字→奮う。日本語の漢字「奮（フン）」の簡体字。" },
  "奖": { radical: "大", radicalMeaning: "だい", components: ["奖"], note: "奬の簡体字→褒美·賞。日本語の漢字「奨（ショウ）」の簡体字に類似。" },
  "姓": { radical: "女", radicalMeaning: "おんなへん", components: ["女", "生"], note: "名前·名字。日本語の漢字「姓（セイ）」と同じ。" },
  "存": { radical: "子", radicalMeaning: "こ", components: ["存"], note: "存在·保存。日本語の漢字「存（ソン）」と同じ。" },
  "完": { radical: "宀", radicalMeaning: "うかんむり", components: ["宀", "元"], note: "完全·終わる。日本語の漢字「完（カン）」と同じ。" },
  "宗": { radical: "宀", radicalMeaning: "うかんむり", components: ["宀", "示"], note: "宗派·宗教。日本語の漢字「宗（シュウ）」と同じ。" },
  "宜": { radical: "宀", radicalMeaning: "うかんむり", components: ["宀", "且"], note: "宜しい→適切。「便宜」で便利。" },
  "害": { radical: "宀", radicalMeaning: "うかんむり", components: ["宀", "丰", "口"], note: "害。日本語の漢字「害（ガイ）」と同じ。" },
  "宾": { radical: "宀", radicalMeaning: "うかんむり", components: ["宀", "兵の略"], note: "賓の簡体字→お客様。日本語の漢字「賓（ヒン）」の簡体字。" },
  "寄": { radical: "宀", radicalMeaning: "うかんむり", components: ["宀", "奇"], note: "寄せる·郵送。日本語の漢字「寄（キ・よせる）」と同じ。" },
  "密": { radical: "宀", radicalMeaning: "うかんむり", components: ["宀", "必", "山"], note: "秘密·密。日本語の漢字「密（ミツ）」と同じ。" },
  "寒": { radical: "宀", radicalMeaning: "うかんむり", components: ["宀", "寒"], note: "寒い。日本語の漢字「寒（カン・さむい）」と同じ。" },
  "察": { radical: "宀", radicalMeaning: "うかんむり", components: ["宀", "祭"], note: "察する→観察。日本語の漢字「察（サツ）」と同じ。" },
  "导": { radical: "寸", radicalMeaning: "すん", components: ["巳", "寸"], note: "導く。日本語の漢字「導（ドウ）」の簡体字。" },
  "封": { radical: "寸", radicalMeaning: "すん", components: ["圭", "寸"], note: "封じる·密封。日本語の漢字「封（フウ）」と同じ。" },
  "将": { radical: "寸", radicalMeaning: "すん", components: ["将"], note: "將の簡体字→まさに·将軍。日本語の漢字「将（ショウ）」の簡体字。" },
  "尊": { radical: "寸", radicalMeaning: "すん", components: ["酋", "寸"], note: "尊い·尊重。日本語の漢字「尊（ソン・とうとい）」と同じ。" },
  "尔": { radical: "小", radicalMeaning: "しょう", components: ["尔"], note: "爾の簡体字→なんじ·〜だけ。日本語の漢字「爾（ジ）」の簡体字。" },
  "尝": { radical: "小", radicalMeaning: "しょう", components: ["尝"], note: "嘗の簡体字→試す·味わう。日本語の漢字「嘗（ショウ）」の簡体字。" },
  "尤": { radical: "尢", radicalMeaning: "まげあし", components: ["尤"], note: "尤も·特に。日本語の漢字「尤（ユウ・もっとも）」と同じ。" },
  "就": { radical: "尢", radicalMeaning: "まげあし", components: ["京", "尤"], note: "就く→すぐに。日本語の漢字「就（シュウ・つく）」と同じ。" },
  "尽": { radical: "尸", radicalMeaning: "しかばね", components: ["尽"], note: "盡の簡体字→尽きる。日本語の漢字「尽（ジン）」の簡体字。" },
  "层": { radical: "尸", radicalMeaning: "しかばね", components: ["尸", "云"], note: "層の簡体字→階層。日本語の漢字「層（ソウ）」の簡体字。" },
  "居": { radical: "尸", radicalMeaning: "しかばね", components: ["尸", "古"], note: "居る·住む。「居然」で意外にも。" },
  "展": { radical: "尸", radicalMeaning: "しかばね", components: ["尸", "展の下部"], note: "展覧·展示。日本語の漢字「展（テン）」と同じ。" },
  "巧": { radical: "工", radicalMeaning: "たくみ", components: ["工", "丂"], note: "巧み。日本語の漢字「巧（コウ・たくみ）」と同じ。" },
  "差": { radical: "工", radicalMeaning: "たくみ", components: ["差"], note: "差·違い。日本語の漢字「差（サ・さす）」と同じ。" },
  "帅": { radical: "巾", radicalMeaning: "はば", components: ["帅"], note: "帥の簡体字→かっこいい·元帥。日本語の漢字「帥（スイ）」の簡体字。" },
  "希": { radical: "巾", radicalMeaning: "はば", components: ["乂", "巾"], note: "希少→希望。日本語の漢字「希（キ・まれ）」と同じ。" },
  "带": { radical: "巾", radicalMeaning: "はばへん", components: ["带"], note: "帶の簡体字→帯·持つ。日本語の漢字「帯（タイ）」の簡体字。" },
  "帮": { radical: "巾", radicalMeaning: "はば", components: ["邦", "巾"], note: "幫の簡体字→助ける。日本語の漢字「幫（ホウ）」の簡体字。" },
  "常": { radical: "巾", radicalMeaning: "はば", components: ["尚", "巾"], note: "常に·普通。日本語の漢字「常（ジョウ・つね）」と同じ。" },
  "平": { radical: "干", radicalMeaning: "ほす", components: ["平"], note: "平ら·平和。日本語の漢字「平（ヘイ・たいら）」と同じ。" },
  "并": { radical: "干", radicalMeaning: "ほす", components: ["并"], note: "並の簡体字→並ぶ·そして。日本語の漢字「並（ヘイ）」の簡体字。" },
  "幸": { radical: "干", radicalMeaning: "ほす", components: ["土", "𢆉"], note: "幸せ。日本語の漢字「幸（コウ・しあわせ）」と同じ。" },
  "幽": { radical: "幺", radicalMeaning: "いとがしら", components: ["山", "幺", "幺", "山"], note: "幽か→静か·幽霊。日本語の漢字「幽（ユウ）」と同じ。" },
  "床": { radical: "广", radicalMeaning: "まだれ", components: ["广", "木"], note: "寝台。日本語の漢字「床（ショウ・とこ）」と同じだが、中国語ではベッド。" },
  "序": { radical: "广", radicalMeaning: "まだれ", components: ["广", "予"], note: "順序。日本語の漢字「序（ジョ）」と同じ。" },
  "应": { radical: "广", radicalMeaning: "まだれ", components: ["广", "应"], note: "應の簡体字→応じる·〜べき。日本語の漢字「応（オウ）」の簡体字に類似。" },
  "座": { radical: "广", radicalMeaning: "まだれ", components: ["广", "坐"], note: "座席。日本語の漢字「座（ザ・すわる）」と同じ。" },
  "建": { radical: "廴", radicalMeaning: "えんにょう", components: ["廴", "聿"], note: "建てる。日本語の漢字「建（ケン・たてる）」と同じ。" },
  "弃": { radical: "廾", radicalMeaning: "にじゅうあし", components: ["弃"], note: "棄の簡体字→捨てる。日本語の漢字「棄（キ）」の簡体字。" },
  "式": { radical: "弋", radicalMeaning: "いぐるみ", components: ["弋", "工"], note: "方式·式。日本語の漢字「式（シキ）」と同じ。" },
  "引": { radical: "弓", radicalMeaning: "ゆみ", components: ["弓", "丨"], note: "引く。日本語の漢字「引（イン・ひく）」と同じ。" },
  "弟": { radical: "弓", radicalMeaning: "ゆみ", components: ["弟"], note: "弟。日本語の漢字「弟（テイ・おとうと）」と同じ。" },
  "弹": { radical: "弓", radicalMeaning: "ゆみへん", components: ["弓", "单"], note: "彈の簡体字→弾く·弾丸。日本語の漢字「弾（ダン）」の簡体字。" },
  "当": { radical: "彐", radicalMeaning: "けいがしら", components: ["当"], note: "當の簡体字→当たる·〜すべき。日本語の漢字「当（トウ）」の簡体字に類似。" },
  "形": { radical: "彡", radicalMeaning: "さんづくり", components: ["开", "彡"], note: "形。日本語の漢字「形（ケイ・かたち）」と同じ。" },
  "彩": { radical: "彡", radicalMeaning: "さんづくり", components: ["采", "彡"], note: "色彩。日本語の漢字「彩（サイ・いろどる）」と同じ。" },
  "影": { radical: "彡", radicalMeaning: "さんづくり", components: ["景", "彡"], note: "影。日本語の漢字「影（エイ・かげ）」と同じ。" },
  "往": { radical: "彳", radicalMeaning: "ぎょうにんべん", components: ["彳", "主"], note: "往く→行く·〜へ。日本語の漢字「往（オウ）」と同じ。" },
  "很": { radical: "彳", radicalMeaning: "ぎょうにんべん", components: ["彳", "艮"], note: "とても。程度副詞。日本語の漢字「很（コン）」に相当。" },
  "律": { radical: "彳", radicalMeaning: "ぎょうにんべん", components: ["彳", "聿"], note: "法律·規則。日本語の漢字「律（リツ）」と同じ。" },
  "微": { radical: "彳", radicalMeaning: "ぎょうにんべん", components: ["彳", "微"], note: "微か→わずか·微信。日本語の漢字「微（ビ）」と同じ。" },
  "必": { radical: "心", radicalMeaning: "こころ", components: ["心", "丿"], note: "必ず。日本語の漢字「必（ヒツ・かならず）」と同じ。" },
  "忆": { radical: "心（忄）", radicalMeaning: "りっしんべん", components: ["忄", "乙"], note: "憶の簡体字→思い出す。日本語の漢字「憶（オク）」の簡体字。" },
  "怀": { radical: "心（忄）", radicalMeaning: "りっしんべん", components: ["忄", "不"], note: "懷の簡体字→懐かしむ·心に抱く。日本語の漢字「懐（カイ）」の簡体字。" },
  "性": { radical: "心（忄）", radicalMeaning: "りっしんべん", components: ["忄", "生"], note: "性質·性別。日本語の漢字「性（セイ）」と同じ。" },
  "怪": { radical: "心（忄）", radicalMeaning: "りっしんべん", components: ["忄", "圣"], note: "怪しい·不思議。「怪不得」で道理で。" },
  "戏": { radical: "戈", radicalMeaning: "ほこづくり", components: ["又", "戈"], note: "戯の簡体字→芝居·遊ぶ。日本語の漢字「戯（ギ）」の簡体字。" },
  "戚": { radical: "戈", radicalMeaning: "ほこづくり", components: ["戚"], note: "親戚。日本語の漢字「戚（セキ）」と同じ。" },
  "戴": { radical: "戈", radicalMeaning: "ほこづくり", components: ["戴"], note: "戴く→帽子をかぶる·尊敬。日本語の漢字「戴（タイ・いただく）」と同じ。" },
  "才": { radical: "手（扌）", radicalMeaning: "てへん", components: ["才"], note: "才能·〜して初めて。日本語の漢字「才（サイ）」と同じ。" },
  "扮": { radical: "手（扌）", radicalMeaning: "てへん", components: ["扌", "分"], note: "扮する→変装·装う。「打扮」でおしゃれ。" },
  "支": { radical: "支", radicalMeaning: "しにょう", components: ["十", "又"], note: "支える·支払う。日本語の漢字「支（シ・ささえる）」と同じ。" },
  "料": { radical: "斗", radicalMeaning: "ます", components: ["米", "斗"], note: "材料·料金。日本語の漢字「料（リョウ）」と同じ。" },
  "末": { radical: "木", radicalMeaning: "き", components: ["一", "木"], note: "末·終わり。「周末」で週末。日本語の漢字「末（マツ・すえ）」と同じ。" },
  "本": { radical: "木", radicalMeaning: "き", components: ["木", "一"], note: "本·元。「日本」で日本。日本語の漢字「本（ホン・もと）」と同じ。" },
  "术": { radical: "木", radicalMeaning: "き", components: ["术"], note: "術の簡体字→技術。日本語の漢字「術（ジュツ）」の簡体字。" },
  "朵": { radical: "木", radicalMeaning: "き", components: ["几", "木"], note: "花の量詞。日本語の漢字「朵（ダ）」に相当。" },
  "李": { radical: "木", radicalMeaning: "き", components: ["木", "子"], note: "すもも·名字。日本語の漢字「李（リ・すもも）」と同じ。" },
  "材": { radical: "木", radicalMeaning: "きへん", components: ["木", "才"], note: "材料。日本語の漢字「材（ザイ）」と同じ。" },
  "束": { radical: "木", radicalMeaning: "き", components: ["束"], note: "束ねる。日本語の漢字「束（ソク・たば）」と同じ。" },
  "松": { radical: "木", radicalMeaning: "きへん", components: ["木", "公"], note: "松·リラックス。日本語の漢字「松（ショウ・まつ）」と同じ。" },
  "板": { radical: "木", radicalMeaning: "きへん", components: ["木", "反"], note: "板→「老板」で社長。日本語の漢字「板（バン・いた）」と同じ。" },
  "极": { radical: "木", radicalMeaning: "きへん", components: ["木", "及"], note: "極の簡体字→極めて·とても。日本語の漢字「極（キョク）」の簡体字。" },
  "染": { radical: "木", radicalMeaning: "き", components: ["氵", "九", "木"], note: "染める。日本語の漢字「染（セン・そめる）」と同じ。" },
  "查": { radical: "木", radicalMeaning: "き", components: ["木", "旦"], note: "調べる。日本語の漢字「査（サ）」の簡体字。" },
  "柿": { radical: "木", radicalMeaning: "きへん", components: ["木", "市"], note: "柿。日本語の漢字「柿（シ・かき）」と同じ。" },
  "标": { radical: "木", radicalMeaning: "きへん", components: ["木", "示"], note: "標の簡体字→標識。日本語の漢字「標（ヒョウ）」の簡体字。" },
  "样": { radical: "木", radicalMeaning: "きへん", components: ["木", "羊"], note: "樣の簡体字→様子。「怎么样」でどう。" },
  "根": { radical: "木", radicalMeaning: "きへん", components: ["木", "艮"], note: "根。日本語の漢字「根（コン・ね）」と同じ。" },
  "案": { radical: "木", radicalMeaning: "き", components: ["安", "木"], note: "案件·案。日本語の漢字「案（アン）」と同じ。" },
  "桌": { radical: "木", radicalMeaning: "き", components: ["桌"], note: "机·テーブル。日本語の漢字「桌（タク）」に相当。" },
  "桶": { radical: "木", radicalMeaning: "きへん", components: ["木", "甬"], note: "桶。日本語の漢字「桶（トウ・おけ）」と同じ。" },
  "梦": { radical: "木", radicalMeaning: "き", components: ["林", "夕"], note: "夢の簡体字→夢。日本語の漢字「夢（ム）」の簡体字。" },
  "梯": { radical: "木", radicalMeaning: "きへん", components: ["木", "弟"], note: "梯子→階段。日本語の漢字「梯（テイ）」と同じ。" },
  "检": { radical: "木", radicalMeaning: "きへん", components: ["木", "佥"], note: "檢の簡体字→検査。日本語の漢字「検（ケン）」の簡体字。" },
  "棵": { radical: "木", radicalMeaning: "きへん", components: ["木", "果"], note: "木の量詞（一本の木）。" },
  "椅": { radical: "木", radicalMeaning: "きへん", components: ["木", "奇"], note: "椅子。日本語の漢字「椅（イ）」と同じ。" },
  "植": { radical: "木", radicalMeaning: "きへん", components: ["木", "直"], note: "植える·植物。日本語の漢字「植（ショク・うえる）」と同じ。" },
  "楚": { radical: "木", radicalMeaning: "き", components: ["林", "疋"], note: "楚楚→清楚。日本語の漢字「楚（ソ）」と同じ。" },
  "概": { radical: "木", radicalMeaning: "きへん", components: ["木", "既"], note: "概して→大体。日本語の漢字「概（ガイ）」と同じ。" },
  "橡": { radical: "木", radicalMeaning: "きへん", components: ["木", "象"], note: "橡の木→ゴム。日本語の漢字「橡（ショウ）」と同じ。" },
  "次": { radical: "欠", radicalMeaning: "あくび", components: ["冫", "欠"], note: "次·回数。日本語の漢字「次（ジ・つぎ）」と同じ。" },
  "款": { radical: "欠", radicalMeaning: "あくび", components: ["士", "示", "欠"], note: "条項·お金。日本語の漢字「款（カン）」と同じ。" },
  "歉": { radical: "欠", radicalMeaning: "あくび", components: ["兼", "欠"], note: "申し訳ない·不足。日本語の漢字「歉（ケン）」に相当。" },
  "歌": { radical: "欠", radicalMeaning: "あくび", components: ["哥", "欠"], note: "歌。日本語の漢字「歌（カ・うた）」と同じ。" },
  "止": { radical: "止", radicalMeaning: "とめる", components: ["止"], note: "止める。日本語の漢字「止（シ・とめる）」と同じ。" },
  "正": { radical: "止", radicalMeaning: "とめる", components: ["一", "止"], note: "正しい·〜している最中。日本語の漢字「正（セイ・ただしい）」と同じ。" },
  "此": { radical: "止", radicalMeaning: "とめる", components: ["止", "匕"], note: "此れ→これ。日本語の漢字「此（シ・これ）」と同じ。" },
  "每": { radical: "毋", radicalMeaning: "なかれ", components: ["毎"], note: "毎。日本語の漢字「毎（マイ・ごと）」と同じ。" },
  "比": { radical: "比", radicalMeaning: "くらべる", components: ["匕", "匕"], note: "比べる。日本語の漢字「比（ヒ・くらべる）」と同じ。" },
  "毕": { radical: "比", radicalMeaning: "くらべる", components: ["比", "十"], note: "畢の簡体字→終わる·卒業。日本語の漢字「畢（ヒツ）」の簡体字。" },
  "毛": { radical: "毛", radicalMeaning: "け", components: ["毛"], note: "毛。日本語の漢字「毛（モウ・け）」と同じ。" },
  "民": { radical: "氏", radicalMeaning: "うじ", components: ["民"], note: "人民·国民。日本語の漢字「民（ミン・たみ）」と同じ。" },
  "汁": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "十"], note: "汁·ジュース。日本語の漢字「汁（ジュウ・しる）」と同じ。" },
  "求": { radical: "水", radicalMeaning: "みず", components: ["求"], note: "求める。日本語の漢字「求（キュウ・もとめる）」と同じ。" },
  "汗": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "干"], note: "汗。日本語の漢字「汗（カン・あせ）」と同じ。" },
  "江": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "工"], note: "大きな川·長江。日本語の漢字「江（コウ・え）」と同じ。" },
  "污": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "亏の略"], note: "汚れる。日本語の漢字「汚（オ）」の簡体字。" },
  "汽": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "气"], note: "蒸気。日本語の漢字「汽（キ）」と同じ。" },
  "沙": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "少"], note: "砂。日本語の漢字「沙（サ・すな）」と同じ。" },
  "没": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "殳の略"], note: "〜ない（否定）。日本語の漢字「没（ボツ）」と同じ。" },
  "治": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "台"], note: "治める·治療。日本語の漢字「治（チ・おさめる）」と同じ。" },
  "泉": { radical: "水", radicalMeaning: "みず", components: ["白", "水"], note: "泉。日本語の漢字「泉（セン・いずみ）」と同じ。" },
  "泼": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "发"], note: "撒く·活発。日本語の漢字「溌（ハツ）」の簡体字。" },
  "洋": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "羊"], note: "洋·海。日本語の漢字「洋（ヨウ）」と同じ。" },
  "洲": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "州"], note: "大陸·アジア。「亚洲」でアジア。" },
  "济": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "齐"], note: "濟の簡体字→救済·経済。日本語の漢字「済（サイ）」の簡体字。" },
  "浪": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "良"], note: "波。日本語の漢字「浪（ロウ・なみ）」と同じ。" },
  "消": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "肖"], note: "消える。日本語の漢字「消（ショウ・きえる）」と同じ。" },
  "渐": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "斩"], note: "漸の簡体字→次第に。日本語の漢字「漸（ゼン）」の簡体字。" },
  "渴": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "曷"], note: "喉が渇く。日本語の漢字「渇（カツ）」の簡体字。" },
  "演": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "寅"], note: "演じる·上演。日本語の漢字「演（エン）」と同じ。" },
  "漫": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "曼"], note: "漫画·ゆっくり。日本語の漢字「漫（マン）」と同じ。" },
  "激": { radical: "水（氵）", radicalMeaning: "さんずい", components: ["氵", "敫"], note: "激しい·感動。日本語の漢字「激（ゲキ・はげしい）」と同じ。" },
  "片": { radical: "片", radicalMeaning: "かた", components: ["片"], note: "一片·薄いもの。日本語の漢字「片（ヘン・かた）」と同じ。" },
  "牌": { radical: "片", radicalMeaning: "かたへん", components: ["片", "卑"], note: "札·看板。日本語の漢字「牌（ハイ）」と同じ。" },
  "物": { radical: "牛（牜）", radicalMeaning: "うしへん", components: ["牜", "勿"], note: "物。日本語の漢字「物（ブツ・もの）」と同じ。" },
  "状": { radical: "犬（犭）", radicalMeaning: "けものへん", components: ["丬", "犬"], note: "狀の簡体字→状態。日本語の漢字「状（ジョウ）」と同じ。" },
  "猜": { radical: "犬（犭）", radicalMeaning: "けものへん", components: ["犭", "青"], note: "推測する。日本語の漢字「猜（サイ）」に相当。" },
  "玩": { radical: "玉（王）", radicalMeaning: "たまへん", components: ["王", "元"], note: "遊ぶ。日本語の漢字「玩（ガン・もてあそぶ）」と同じ。" },
  "现": { radical: "玉（王）", radicalMeaning: "たまへん", components: ["王", "见"], note: "現の簡体字→現れる·現在。日本語の漢字「現（ゲン）」の簡体字。" },
  "琴": { radical: "玉（王）", radicalMeaning: "たま", components: ["琴"], note: "琴。日本語の漢字「琴（キン・こと）」と同じ。" },
  "甚": { radical: "甘", radicalMeaning: "あまい", components: ["其の略", "匕"], note: "甚だ→非常に。日本語の漢字「甚（ジン・はなはだ）」と同じ。" },
  "甜": { radical: "甘", radicalMeaning: "あまい", components: ["舌", "甘"], note: "甘い。日本語の漢字「甜（テン）」に相当。" },
  "由": { radical: "田", radicalMeaning: "た", components: ["由"], note: "〜から·理由。日本語の漢字「由（ユ・よし）」と同じ。" },
  "申": { radical: "田", radicalMeaning: "た", components: ["申"], note: "申す·申請。日本語の漢字「申（シン・もうす）」と同じ。" },
  "画": { radical: "田", radicalMeaning: "た", components: ["一", "田", "凵"], note: "畫の簡体字→絵。日本語の漢字「画（ガ）」と同じ。" },
  "界": { radical: "田", radicalMeaning: "た", components: ["田", "介"], note: "世界·境界。日本語の漢字「界（カイ）」と同じ。" },
  "留": { radical: "田", radicalMeaning: "た", components: ["留"], note: "留まる·残す。日本語の漢字「留（リュウ・とどまる）」と同じ。" },
  "疑": { radical: "疋", radicalMeaning: "ひき", components: ["疑"], note: "疑う。日本語の漢字「疑（ギ・うたがう）」と同じ。" },
  "盒": { radical: "皿", radicalMeaning: "さら", components: ["合", "皿"], note: "箱·ケース。「饭盒」で弁当箱。" },
  "矿": { radical: "石", radicalMeaning: "いしへん", components: ["石", "广"], note: "礦の簡体字→鉱物。日本語の漢字「鉱（コウ）」の簡体字。" },
  "码": { radical: "石", radicalMeaning: "いしへん", components: ["石", "马"], note: "碼の簡体字→番号·パスワード。日本語の漢字「碼（マ）」の簡体字。" },
  "研": { radical: "石", radicalMeaning: "いしへん", components: ["石", "开"], note: "研ぐ→研究。日本語の漢字「研（ケン・とぐ）」と同じ。" },
  "破": { radical: "石", radicalMeaning: "いしへん", components: ["石", "皮"], note: "破る。日本語の漢字「破（ハ・やぶる）」と同じ。" },
  "础": { radical: "石", radicalMeaning: "いしへん", components: ["石", "出"], note: "礎の簡体字→基礎。日本語の漢字「礎（ソ）」の簡体字。" },
  "硕": { radical: "石", radicalMeaning: "いしへん", components: ["石", "页"], note: "碩の簡体字→大きい·修士。日本語の漢字「碩（セキ）」の簡体字。" },
  "确": { radical: "石", radicalMeaning: "いしへん", components: ["石", "角"], note: "確の簡体字→確か。日本語の漢字「確（カク）」の簡体字。" },
  "示": { radical: "示", radicalMeaning: "しめす", components: ["示"], note: "示す。日本語の漢字「示（ジ・しめす）」と同じ。" },
  "社": { radical: "示（礻）", radicalMeaning: "しめすへん", components: ["礻", "土"], note: "社会·会社。日本語の漢字「社（シャ）」と同じ。" },
  "祖": { radical: "示（礻）", radicalMeaning: "しめすへん", components: ["礻", "且"], note: "祖先。日本語の漢字「祖（ソ）」と同じ。" },
  "祝": { radical: "示（礻）", radicalMeaning: "しめすへん", components: ["礻", "兄"], note: "祝う。日本語の漢字「祝（シュク・いわう）」と同じ。" },
  "禁": { radical: "示", radicalMeaning: "しめす", components: ["林", "示"], note: "禁止。日本語の漢字「禁（キン）」と同じ。" },
  "福": { radical: "示（礻）", radicalMeaning: "しめすへん", components: ["礻", "畐"], note: "福。日本語の漢字「福（フク）」と同じ。" },
  "离": { radical: "禸", radicalMeaning: "ぐうのあし", components: ["离"], note: "離の簡体字→離れる·距離。日本語の漢字「離（リ）」の簡体字。" },
  "秀": { radical: "禾", radicalMeaning: "のぎへん", components: ["禾", "乃"], note: "秀でる。日本語の漢字「秀（シュウ・ひいでる）」と同じ。" },
  "种": { radical: "禾", radicalMeaning: "のぎへん", components: ["禾", "中"], note: "種の簡体字→種類·植える。日本語の漢字「種（シュ）」の簡体字。" },
  "秒": { radical: "禾", radicalMeaning: "のぎへん", components: ["禾", "少"], note: "秒。日本語の漢字「秒（ビョウ）」と同じ。" },
  "积": { radical: "禾", radicalMeaning: "のぎへん", components: ["禾", "只"], note: "積の簡体字→積む。日本語の漢字「積（セキ）」の簡体字。" },
  "程": { radical: "禾", radicalMeaning: "のぎへん", components: ["禾", "呈"], note: "程度·道程。日本語の漢字「程（テイ・ほど）」と同じ。" },
  "稍": { radical: "禾", radicalMeaning: "のぎへん", components: ["禾", "肖"], note: "稍や→少し。「稍微」で少し。" },
  "究": { radical: "穴", radicalMeaning: "あなかんむり", components: ["穴", "九"], note: "研究·究める。日本語の漢字「究（キュウ・きわめる）」と同じ。" },
  "穷": { radical: "穴", radicalMeaning: "あなかんむり", components: ["穴", "力"], note: "窮の簡体字→貧しい。日本語の漢字「窮（キュウ）」の簡体字。" },
  "穿": { radical: "穴", radicalMeaning: "あなかんむり", components: ["穴", "牙"], note: "着る·穿つ。日本語の漢字「穿（セン・うがつ）」と同じ。" },
  "突": { radical: "穴", radicalMeaning: "あなかんむり", components: ["穴", "犬"], note: "突然。日本語の漢字「突（トツ・つく）」と同じ。" },
  "窄": { radical: "穴", radicalMeaning: "あなかんむり", components: ["穴", "乍"], note: "狭い。日本語の漢字「窄（サク・せまい）」と同じ。" },
  "竞": { radical: "立", radicalMeaning: "たつ", components: ["立", "兄"], note: "競の簡体字→競う。日本語の漢字「競（キョウ）」の簡体字。" },
  "竟": { radical: "立", radicalMeaning: "たつ", components: ["音の略", "儿"], note: "竟に→ついに。「毕竟」で結局。" },
  "章": { radical: "立", radicalMeaning: "たつ", components: ["立", "早"], note: "文章·章。日本語の漢字「章（ショウ）」と同じ。" },
  "童": { radical: "立", radicalMeaning: "たつ", components: ["立", "里"], note: "童→子供。日本語の漢字「童（ドウ・わらべ）」と同じ。" },
  "竹": { radical: "竹", radicalMeaning: "たけ", components: ["竹"], note: "竹。日本語の漢字「竹（チク・たけ）」と同じ。" },
  "笔": { radical: "竹（⺮）", radicalMeaning: "たけかんむり", components: ["⺮", "毛"], note: "筆の簡体字→ペン。日本語の漢字「筆（ヒツ）」の簡体字。" },
  "符": { radical: "竹（⺮）", radicalMeaning: "たけかんむり", components: ["⺮", "付"], note: "符号·符合。日本語の漢字「符（フ）」と同じ。" },
  "笨": { radical: "竹（⺮）", radicalMeaning: "たけかんむり", components: ["⺮", "本"], note: "愚か·不器用。日本語の漢字「笨（ホン）」に相当。" },
  "等": { radical: "竹（⺮）", radicalMeaning: "たけかんむり", components: ["⺮", "寺"], note: "等しい·〜など·待つ。日本語の漢字「等（トウ・ひとしい）」と同じ。" },
  "签": { radical: "竹（⺮）", radicalMeaning: "たけかんむり", components: ["⺮", "佥"], note: "簽の簡体字→サイン·くじ。日本語の漢字「簽（セン）」の簡体字。" },
  "算": { radical: "竹（⺮）", radicalMeaning: "たけかんむり", components: ["⺮", "目", "廾"], note: "計算。日本語の漢字「算（サン）」と同じ。" },
  "管": { radical: "竹（⺮）", radicalMeaning: "たけかんむり", components: ["⺮", "官"], note: "管·管理。日本語の漢字「管（カン・くだ）」と同じ。" },
  "箱": { radical: "竹（⺮）", radicalMeaning: "たけかんむり", components: ["⺮", "相"], note: "箱。日本語の漢字「箱（ソウ・はこ）」と同じだが、⺮が冠。" },
  "籍": { radical: "竹（⺮）", radicalMeaning: "たけかんむり", components: ["⺮", "耤"], note: "書籍·国籍。日本語の漢字「籍（セキ）」と同じ。" },
  "粗": { radical: "米", radicalMeaning: "こめへん", components: ["米", "且"], note: "粗い·粗末。日本語の漢字「粗（ソ・あらい）」と同じ。" },
  "精": { radical: "米", radicalMeaning: "こめへん", components: ["米", "青"], note: "精緻→精密·精力。日本語の漢字「精（セイ）」と同じ。" },
  "紧": { radical: "糸", radicalMeaning: "いと", components: ["紧"], note: "緊の簡体字→緊急·きつい。日本語の漢字「緊（キン）」の簡体字。" },
  "纪": { radical: "糸（纟）", radicalMeaning: "いとへん", components: ["纟", "己"], note: "紀の簡体字→記録·世紀。日本語の漢字「紀（キ）」の簡体字。" },
  "纸": { radical: "糸（纟）", radicalMeaning: "いとへん", components: ["纟", "氏"], note: "紙。日本語の漢字「紙（シ）」の簡体字。" },
  "线": { radical: "糸（纟）", radicalMeaning: "いとへん", components: ["纟", "戋"], note: "線の簡体字→線。日本語の漢字「線（セン）」の簡体字。" },
  "组": { radical: "糸（纟）", radicalMeaning: "いとへん", components: ["纟", "且"], note: "組の簡体字→組む·グループ。日本語の漢字「組（ソ）」の簡体字。" },
  "细": { radical: "糸（纟）", radicalMeaning: "いとへん", components: ["纟", "田"], note: "細の簡体字→細い。日本語の漢字「細（サイ）」の簡体字。" },
  "终": { radical: "糸（纟）", radicalMeaning: "いとへん", components: ["纟", "冬"], note: "終の簡体字→終わり。日本語の漢字「終（シュウ）」の簡体字。" },
  "结": { radical: "糸（纟）", radicalMeaning: "いとへん", components: ["纟", "吉"], note: "結の簡体字→結ぶ·結果。日本語の漢字「結（ケツ）」の簡体字。" },
  "绝": { radical: "糸（纟）", radicalMeaning: "いとへん", components: ["纟", "色"], note: "絕の簡体字→絶つ·絶対。日本語の漢字「絶（ゼツ）」の簡体字。" },
  "统": { radical: "糸（纟）", radicalMeaning: "いとへん", components: ["纟", "充"], note: "統の簡体字→統べる·系統。日本語の漢字「統（トウ）」の簡体字。" },
  "继": { radical: "糸（纟）", radicalMeaning: "いとへん", components: ["纟", "继の右部"], note: "繼の簡体字→継ぐ。日本語の漢字「継（ケイ）」の簡体字。" },
  "绩": { radical: "糸（纟）", radicalMeaning: "いとへん", components: ["纟", "责"], note: "績の簡体字→成績。日本語の漢字「績（セキ）」の簡体字。" },
  "缺": { radical: "缶", radicalMeaning: "ほとぎ", components: ["缶", "夬"], note: "欠ける·不足。日本語の漢字「缺（ケツ）」の簡体字·欠。" },
  "网": { radical: "网", radicalMeaning: "あみがしら", components: ["网"], note: "網の簡体字→ネット·網。日本語の漢字「網（モウ）」の簡体字。" },
  "美": { radical: "羊", radicalMeaning: "ひつじ", components: ["羊", "大"], note: "美しい·アメリカ。日本語の漢字「美（ビ・うつくしい）」と同じ。" },
  "羞": { radical: "羊", radicalMeaning: "ひつじ", components: ["羊", "丑"], note: "恥ずかしい。日本語の漢字「羞（シュウ）」と同じ。" },
  "羡": { radical: "羊", radicalMeaning: "ひつじ", components: ["羊", "次"], note: "羨の簡体字→羨む。日本語の漢字「羨（セン）」の簡体字。" },
  "羽": { radical: "羽", radicalMeaning: "はね", components: ["羽"], note: "羽。日本語の漢字「羽（ウ・はね）」と同じ。" },
  "翻": { radical: "羽", radicalMeaning: "はね", components: ["番", "羽"], note: "翻訳·ひっくり返す。日本語の漢字「翻（ホン・ひるがえる）」と同じ。" },
  "老": { radical: "老", radicalMeaning: "おいかんむり", components: ["老"], note: "老いる。日本語の漢字「老（ロウ・おいる）」と同じ。" },
  "者": { radical: "老", radicalMeaning: "おいかんむり", components: ["者"], note: "者。日本語の漢字「者（シャ・もの）」と同じ。" },
  "而": { radical: "而", radicalMeaning: "しこうして", components: ["而"], note: "而して→そして·だが。日本語の漢字「而（ジ・しかして）」と同じ。" },
  "耐": { radical: "而", radicalMeaning: "しこうして", components: ["而", "寸"], note: "耐える。日本語の漢字「耐（タイ・たえる）」と同じ。" },
  "聊": { radical: "耳", radicalMeaning: "みみへん", components: ["耳", "卯"], note: "話す（口語）·つまらない。「无聊」で退屈。" },
  "职": { radical: "耳", radicalMeaning: "みみへん", components: ["耳", "只"], note: "職の簡体字→職業。日本語の漢字「職（ショク）」の簡体字。" },
  "聘": { radical: "耳", radicalMeaning: "みみへん", components: ["耳", "甹"], note: "招聘→採用。日本語の漢字「聘（ヘイ）」と同じ。" },
  "聚": { radical: "耳", radicalMeaning: "みみ", components: ["取", "乑"], note: "集まる。日本語の漢字「聚（シュウ）」と同じ。" },
  "聪": { radical: "耳", radicalMeaning: "みみへん", components: ["耳", "总"], note: "聰の簡体字→賢い。日本語の漢字「聡（ソウ）」の簡体字。" },
  "脱": { radical: "月", radicalMeaning: "にくづき", components: ["月", "兑"], note: "脱ぐ·離れる。日本語の漢字「脱（ダツ・ぬぐ）」と同じ。" },
  "至": { radical: "至", radicalMeaning: "いたる", components: ["至"], note: "至る。日本語の漢字「至（シ・いたる）」と同じ。" },
  "航": { radical: "舟", radicalMeaning: "ふねへん", components: ["舟", "亢"], note: "航行·航空。日本語の漢字「航（コウ）」と同じ。" },
  "般": { radical: "舟", radicalMeaning: "ふねへん", components: ["舟", "殳"], note: "般→種類·〜のような。「一般」で一般。" },
  "船": { radical: "舟", radicalMeaning: "ふねへん", components: ["舟", "㕣"], note: "船。日本語の漢字「船（セン・ふね）」と同じ。" },
  "色": { radical: "色", radicalMeaning: "いろ", components: ["色"], note: "色。日本語の漢字「色（ショク・いろ）」と同じ。" },
  "衫": { radical: "衣（衤）", radicalMeaning: "ころもへん", components: ["衤", "彡"], note: "シャツ。「衬衫」でワイシャツ。" },
  "衬": { radical: "衣（衤）", radicalMeaning: "ころもへん", components: ["衤", "寸"], note: "襯の簡体字→裏地·シャツ。" },
  "袋": { radical: "衣", radicalMeaning: "ころも", components: ["代", "衣"], note: "袋。日本語の漢字「袋（タイ・ふくろ）」と同じ。" },
  "覽": { radical: "見", radicalMeaning: "みる", components: ["覽"], note: "見る（繁体字·一部の文脈で使用）。" },
  "角": { radical: "角", radicalMeaning: "つの", components: ["角"], note: "角·コーナー。日本語の漢字「角（カク・かど）」と同じ。" },
  "言": { radical: "言", radicalMeaning: "ことば", components: ["言"], note: "言葉。日本語の漢字「言（ゲン・ことば）」と同じ。" },
  "语": { radical: "言（讠）", radicalMeaning: "ごんべん", components: ["讠", "吾"], note: "語の簡体字→言語。日本語の漢字「語（ゴ）」の簡体字。" },
  "象": { radical: "豕", radicalMeaning: "いのこ", components: ["象"], note: "象·かたち。日本語の漢字「象（ショウ・ゾウ）」と同じ。" },
  "豪": { radical: "豕", radicalMeaning: "いのこ", components: ["高の略", "豕"], note: "豪華·豪快。日本語の漢字「豪（ゴウ）」と同じ。" },
  "貌": { radical: "豸", radicalMeaning: "むじなへん", components: ["豸", "皃"], note: "容貌·外見。日本語の漢字「貌（ボウ）」と同じ。" },
  "负": { radical: "貝（贝）", radicalMeaning: "かい", components: ["⺈", "贝"], note: "負の簡体字→負う。日本語の漢字「負（フ）」の簡体字。" },
  "责": { radical: "貝（贝）", radicalMeaning: "かい", components: ["责"], note: "責の簡体字→責任。日本語の漢字「責（セキ）」の簡体字。" },
  "货": { radical: "貝（贝）", radicalMeaning: "かいへん", components: ["化", "贝"], note: "貨の簡体字→商品·貨物。日本語の漢字「貨（カ）」の簡体字。" },
  "购": { radical: "貝（贝）", radicalMeaning: "かいへん", components: ["贝", "勾"], note: "購の簡体字→買う。日本語の漢字「購（コウ）」の簡体字。" },
  "费": { radical: "貝（贝）", radicalMeaning: "かい", components: ["弗", "贝"], note: "費の簡体字→費用。日本語の漢字「費（ヒ）」の簡体字。" },
  "贺": { radical: "貝（贝）", radicalMeaning: "かい", components: ["加", "贝"], note: "賀の簡体字→祝う。日本語の漢字「賀（ガ）」の簡体字。" },
  "资": { radical: "貝（贝）", radicalMeaning: "かい", components: ["次", "贝"], note: "資の簡体字→資金·資本。日本語の漢字「資（シ）」の簡体字。" },
  "赚": { radical: "貝（贝）", radicalMeaning: "かいへん", components: ["贝", "兼"], note: "賺の簡体字→儲ける。日本語の漢字「賺（タン）」の簡体字。" },
  "距": { radical: "足（⻊）", radicalMeaning: "あしへん", components: ["⻊", "巨"], note: "距離。日本語の漢字「距（キョ）」と同じ。" },
  "都": { radical: "邑（阝）", radicalMeaning: "おおざと", components: ["者", "阝"], note: "都·全て。日本語の漢字「都（ト・みやこ）」と同じ。" },
  "醉": { radical: "酉", radicalMeaning: "とりへん", components: ["酉", "卒"], note: "醉の簡体字→酔う。日本語の漢字「酔（スイ）」の簡体字·醉。" },
  "释": { radical: "釆", radicalMeaning: "のごめ", components: ["釆", "睪の略"], note: "釋の簡体字→解く·釈放。日本語の漢字「釈（シャク）」の簡体字。" },
  "量": { radical: "里", radicalMeaning: "さと", components: ["旦", "里"], note: "量る。日本語の漢字「量（リョウ・はかる）」と同じ。" },
  "间": { radical: "門（门）", radicalMeaning: "もんがまえ", components: ["门", "日"], note: "間の簡体字→間。日本語の漢字「間（カン）」の簡体字。" },
  "阅": { radical: "門（门）", radicalMeaning: "もんがまえ", components: ["门", "兑"], note: "閱の簡体字→閲読·見る。日本語の漢字「閲（エツ）」の簡体字。" },
  "队": { radical: "阜（阝）", radicalMeaning: "こざとへん", components: ["阝", "人"], note: "隊の簡体字→隊。日本語の漢字「隊（タイ）」の簡体字。" },
  "阳": { radical: "阜（阝）", radicalMeaning: "こざとへん", components: ["阝", "日"], note: "陽の簡体字→陽·太陽。日本語の漢字「陽（ヨウ）」の簡体字。" },
  "阴": { radical: "阜（阝）", radicalMeaning: "こざとへん", components: ["阝", "月"], note: "陰の簡体字→陰。日本語の漢字「陰（イン）」の簡体字。" },
  "阻": { radical: "阜（阝）", radicalMeaning: "こざとへん", components: ["阝", "且"], note: "阻む。日本語の漢字「阻（ソ・はばむ）」と同じ。" },
  "阿": { radical: "阜（阝）", radicalMeaning: "こざとへん", components: ["阝", "可"], note: "阿→接頭語·親しみ。日本語の漢字「阿（ア）」と同じ。" },
  "降": { radical: "阜（阝）", radicalMeaning: "こざとへん", components: ["阝", "夅"], note: "降りる·下げる。日本語の漢字「降（コウ・おりる）」と同じ。" },
  "限": { radical: "阜（阝）", radicalMeaning: "こざとへん", components: ["阝", "艮"], note: "限る。日本語の漢字「限（ゲン・かぎる）」と同じ。" },
  "险": { radical: "阜（阝）", radicalMeaning: "こざとへん", components: ["阝", "佥"], note: "險の簡体字→危険。日本語の漢字「険（ケン）」の簡体字。" },
  "随": { radical: "阜（阝）", radicalMeaning: "こざとへん", components: ["阝", "迶"], note: "隨の簡体字→従う·〜に連れて。日本語の漢字「随（ズイ）」の簡体字。" },
  "需": { radical: "雨", radicalMeaning: "あめかんむり", components: ["雨", "而"], note: "必要·需要。日本語の漢字「需（ジュ）」と同じ。" },
  "静": { radical: "青", radicalMeaning: "あお", components: ["青", "争"], note: "静の簡体字→静か。日本語の漢字「静（セイ）」の簡体字。" },
  "非": { radical: "非", radicalMeaning: "あらず", components: ["非"], note: "非ず→〜ではない。日本語の漢字「非（ヒ）」と同じ。" },
  "面": { radical: "面", radicalMeaning: "めん", components: ["面"], note: "面·顔。日本語の漢字「面（メン・おもて）」と同じ。" },
  "音": { radical: "音", radicalMeaning: "おと", components: ["立", "日"], note: "音·音楽。日本語の漢字「音（オン・おと）」と同じ。" },
  "顺": { radical: "頁（页）", radicalMeaning: "おおがい", components: ["川", "页"], note: "順の簡体字→順序。日本語の漢字「順（ジュン）」の簡体字。" },
  "须": { radical: "頁（页）", radicalMeaning: "おおがい", components: ["彡", "页"], note: "須の簡体字→必ず·髭。日本語の漢字「須（ス）」の簡体字。" },
  "颜": { radical: "頁（页）", radicalMeaning: "おおがい", components: ["彦", "页"], note: "顏の簡体字→顔·色。日本語の漢字「顔（ガン）」の簡体字。" },
  "餐": { radical: "食", radicalMeaning: "しょく", components: ["餐"], note: "食事。日本語の漢字「餐（サン）」に相当。" },
  "饮": { radical: "食（饣）", radicalMeaning: "しょくへん", components: ["饣", "欠"], note: "飲の簡体字→飲む。日本語の漢字「飲（イン）」の簡体字。" },
  "饼": { radical: "食（饣）", radicalMeaning: "しょくへん", components: ["饣", "并"], note: "餅の簡体字→餅·パン。日本語の漢字「餅（ヘイ）」の簡体字。" },
  "首": { radical: "首", radicalMeaning: "くび", components: ["首"], note: "首·最初。日本語の漢字「首（シュ・くび）」と同じ。" },
  "香": { radical: "香", radicalMeaning: "かおり", components: ["禾", "日"], note: "香り·美味しい。日本語の漢字「香（コウ・かおり）」と同じ。" },
  "骄": { radical: "馬（马）", radicalMeaning: "うまへん", components: ["马", "乔"], note: "驕の簡体字→驕る·誇り。日本語の漢字「驕（キョウ）」の簡体字。" },
  "骑": { radical: "馬（马）", radicalMeaning: "うまへん", components: ["马", "奇"], note: "騎の簡体字→乗る。日本語の漢字「騎（キ）」の簡体字。" },
  "骗": { radical: "馬（马）", radicalMeaning: "うまへん", components: ["马", "扁"], note: "騙の簡体字→騙す。日本語の漢字「騙（ヘン）」の簡体字。" },
  "鲜": { radical: "魚（鱼）", radicalMeaning: "うおへん", components: ["鱼", "羊"], note: "鮮の簡体字→新鮮。日本語の漢字「鮮（セン）」の簡体字。" },
  "麻": { radical: "麻", radicalMeaning: "あさ", components: ["广", "林"], note: "麻·痺れる。日本語の漢字「麻（マ・あさ）」と同じ。" },
  "默": { radical: "黑", radicalMeaning: "くろ", components: ["黑", "犬"], note: "黙の簡体字→黙る。日本語の漢字「黙（モク）」の簡体字に類似。" },
  "鼓": { radical: "鼓", radicalMeaning: "つづみ", components: ["鼓"], note: "鼓·太鼓→励ます。日本語の漢字「鼓（コ・つづみ）」と同じ。" },
  "龄": { radical: "齒（齿）", radicalMeaning: "はへん", components: ["齿", "令"], note: "齡の簡体字→年齢。日本語の漢字「齢（レイ）」の簡体字。" },
  "历": { radical: "厂", radicalMeaning: "がんだれ", components: ["厂", "力"], note: "歴史·カレンダー。" },
  "松": { radical: "木", radicalMeaning: "きへん", components: ["木", "公"], note: "松の木·リラックス。日本語の漢字「松（ショウ・まつ）」と同じ。" },
  "纪": { radical: "糸（纟）", radicalMeaning: "いとへん", components: ["纟", "己"], note: "紀→世紀·規律。" }
};

// ── 生成処理 ──
console.log('Adding ' + Object.keys(remainingHanzi).length + ' remaining hanzi breakdown entries...');

// 既存の hanziBreakdown.json を読み込んでマージ
const breakdownPath = path.join(__dirname, '..', 'src', 'data', 'hanziBreakdown.json');
const existingBreakdown = require(breakdownPath);

// マージ（既存優先）
const mergedBreakdown = { ...remainingHanzi, ...existingBreakdown };

fs.writeFileSync(breakdownPath, JSON.stringify(mergedBreakdown, null, 2));
console.log('Hanzi breakdown done! Total entries:', Object.keys(mergedBreakdown).length);

// ── 語源・覚え方の生成 ──
const wordsPath = path.join(__dirname, '..', 'src', 'data', 'words.json');
const wordsData = require(wordsPath);
const hanziMap = mergedBreakdown;

function generateEtymology(word) {
  const chars = [...word.hanzi];
  const parts = chars.map(c => {
    const info = hanziMap[c];
    if (info) return `「${c}」（${info.radical}：${info.radicalMeaning}）`;
    return `「${c}」`;
  });
  return `${parts.join('＋')}。${word.meaning}を表す。`;
}

function generateMnemonic(word) {
  const chars = [...word.hanzi];
  const parts = chars.map(c => {
    const info = hanziMap[c];
    if (info && info.radicalMeaning) {
      return `${c}（${info.radicalMeaning}）`;
    }
    return c;
  });
  
  // ピンインから日本語類似音を探す
  const pinyin = word.pinyin.replace(/\s+/g, '');
  const soundHints = [];
  
  // ピンインの音節を日本語の音読みに近い形で表現
  const syllableMap = {
    'ai': 'アイ', 'an': 'アン', 'ang': 'アン', 'ao': 'アオ',
    'ba': 'ハ', 'bai': 'ハイ', 'ban': 'ハン', 'bang': 'ホウ', 'bao': 'ホウ', 'bei': 'ハイ', 'ben': 'ホン', 'bi': 'ヒ', 'bian': 'ヘン', 'biao': 'ヒョウ', 'bie': 'ベツ', 'bin': 'ヒン', 'bing': 'ヘイ', 'bo': 'ハク',
    'bu': 'フ',
    'ca': 'サツ', 'cai': 'サイ', 'can': 'サン', 'cang': 'ソウ', 'cao': 'ソウ', 'ce': 'サク', 'ceng': 'ソウ', 'cha': 'サ', 'chai': 'サイ', 'chan': 'セン', 'chang': 'チョウ', 'chao': 'チョウ', 'che': 'シャ', 'chen': 'シン', 'cheng': 'セイ', 'chi': 'ショク', 'chong': 'ジュウ', 'chou': 'チュウ', 'chu': 'シュツ', 'chuai': 'サイ', 'chuan': 'セン', 'chuang': 'ソウ', 'chui': 'スイ', 'chun': 'シュン', 'chuo': 'タク', 'ci': 'シ', 'cong': 'ソウ', 'cou': 'ソウ', 'cu': 'ソク', 'cuan': 'サン', 'cui': 'サイ', 'cun': 'ソン', 'cuo': 'サク',
    'da': 'ダ', 'dai': 'ダイ', 'dan': 'タン', 'dang': 'トウ', 'dao': 'トウ', 'de': 'トク', 'dei': 'ダイ', 'den': 'トン', 'deng': 'トウ', 'di': 'テキ', 'dian': 'テン', 'diao': 'チョウ', 'die': 'ジョウ', 'ding': 'テイ', 'diu': 'チュウ', 'dong': 'トウ', 'dou': 'トウ', 'du': 'トク', 'duan': 'タン', 'dui': 'タイ', 'dun': 'トン', 'duo': 'タ',
    'e': 'ガ', 'en': 'オン', 'er': 'ジ',
    'fa': 'ホウ', 'fan': 'ハン', 'fang': 'ホウ', 'fei': 'ヒ', 'fen': 'フン', 'feng': 'フウ', 'fo': 'ブツ', 'fou': 'フ', 'fu': 'フク',
    'ga': 'カツ', 'gai': 'ガイ', 'gan': 'カン', 'gang': 'コウ', 'gao': 'コウ', 'ge': 'カク', 'gei': 'キュウ', 'gen': 'コン', 'geng': 'コウ', 'gong': 'ク', 'gou': 'コウ', 'gu': 'コ', 'gua': 'カツ', 'guai': 'カイ', 'guan': 'カン', 'guang': 'コウ', 'gui': 'キ', 'gun': 'コン', 'guo': 'カ',
    'ha': 'カ', 'hai': 'カイ', 'han': 'カン', 'hang': 'コウ', 'hao': 'コウ', 'he': 'カ', 'hei': 'コク', 'hen': 'コン', 'heng': 'コウ', 'hong': 'コウ', 'hou': 'コウ', 'hu': 'コ', 'hua': 'カ', 'huai': 'カイ', 'huan': 'カン', 'huang': 'コウ', 'hui': 'カイ', 'hun': 'コン', 'huo': 'カツ',
    'ji': 'キ', 'jia': 'カ', 'jian': 'ケン', 'jiang': 'コウ', 'jiao': 'コウ', 'jie': 'カイ', 'jin': 'キン', 'jing': 'ケイ', 'jiong': 'ケイ', 'jiu': 'キュウ', 'ju': 'キョ', 'juan': 'ケン', 'jue': 'カク', 'jun': 'クン',
    'ka': 'カ', 'kai': 'カイ', 'kan': 'カン', 'kang': 'コウ', 'kao': 'コウ', 'ke': 'カク', 'ken': 'コン', 'keng': 'コウ', 'kong': 'クウ', 'kou': 'コウ', 'ku': 'コ', 'kua': 'カ', 'kuai': 'カイ', 'kuan': 'カン', 'kuang': 'コウ', 'kui': 'キ', 'kun': 'コン', 'kuo': 'カク',
    'la': 'ラ', 'lai': 'ライ', 'lan': 'ラン', 'lang': 'ロウ', 'lao': 'ロウ', 'le': 'ラク', 'lei': 'ライ', 'leng': 'ロウ', 'li': 'リ', 'lia': 'リョウ', 'lian': 'レン', 'liang': 'リョウ', 'liao': 'リョウ', 'lie': 'レツ', 'lin': 'リン', 'ling': 'レイ', 'liu': 'リュウ', 'long': 'ロウ', 'lou': 'ロウ', 'lu': 'ロ', 'lv': 'リョ', 'luan': 'ラン', 'lun': 'ロン', 'luo': 'ラ',
    'ma': 'マ', 'mai': 'マイ', 'man': 'マン', 'mang': 'モウ', 'mao': 'モウ', 'me': 'マ', 'mei': 'マイ', 'men': 'モン', 'meng': 'モウ', 'mi': 'ミ', 'mian': 'メン', 'miao': 'ミョウ', 'mie': 'メツ', 'min': 'ミン', 'ming': 'メイ', 'miu': 'ミュウ', 'mo': 'マツ', 'mou': 'モウ', 'mu': 'モク',
    'na': 'ナ', 'nai': 'ナイ', 'nan': 'ナン', 'nang': 'ノウ', 'nao': 'ノウ', 'ne': 'ナ', 'nei': 'ナイ', 'nen': 'ノン', 'neng': 'ノウ', 'ni': 'ニ', 'nian': 'ネン', 'niang': 'ジョウ', 'niao': 'ニョウ', 'nie': 'ネツ', 'nin': 'ニン', 'ning': 'ネイ', 'niu': 'ニュウ', 'nong': 'ノウ', 'nu': 'ヌ', 'nv': 'ジョ', 'nuan': 'ナン', 'nuo': 'ナ',
    'o': 'オ',
    'pa': 'ハ', 'pai': 'ハイ', 'pan': 'ハン', 'pang': 'ホウ', 'pao': 'ホウ', 'pei': 'ハイ', 'pen': 'ホン', 'peng': 'ホウ', 'pi': 'ヒ', 'pian': 'ヘン', 'piao': 'ヒョウ', 'pie': 'ヘツ', 'pin': 'ヒン', 'ping': 'ヘイ', 'po': 'ハ', 'pou': 'ホウ', 'pu': 'ホク',
    'qi': 'キ', 'qia': 'カ', 'qian': 'ケン', 'qiang': 'キョウ', 'qiao': 'キョウ', 'qie': 'セツ', 'qin': 'キン', 'qing': 'セイ', 'qiong': 'ケイ', 'qiu': 'キュウ', 'qu': 'ク', 'quan': 'ケン', 'que': 'カク', 'qun': 'クン',
    'ran': 'ゼン', 'rang': 'ジョウ', 'rao': 'ジョウ', 're': 'ネツ', 'ren': 'ニン', 'reng': 'ジョウ', 'ri': 'ニチ', 'rong': 'ユウ', 'rou': 'ニュウ', 'ru': 'ニュウ', 'ruan': 'ナン', 'rui': 'ゼイ', 'run': 'ジュン', 'ruo': 'ジャク',
    'sa': 'サ', 'sai': 'サイ', 'san': 'サン', 'sang': 'ソウ', 'sao': 'ソウ', 'se': 'ショク', 'sen': 'シン', 'seng': 'ソウ', 'sha': 'サ', 'shai': 'サイ', 'shan': 'セン', 'shang': 'ショウ', 'shao': 'ショウ', 'she': 'シャ', 'shei': 'スイ', 'shen': 'シン', 'sheng': 'セイ', 'shi': 'シ', 'shou': 'シュウ', 'shu': 'ショ', 'shua': 'サ', 'shuai': 'スイ', 'shuan': 'セン', 'shuang': 'ソウ', 'shui': 'スイ', 'shun': 'ジュン', 'shuo': 'セツ', 'si': 'シ', 'song': 'ソウ', 'sou': 'ソウ', 'su': 'ソク', 'suan': 'サン', 'sui': 'スイ', 'sun': 'ソン', 'suo': 'サ',
    'ta': 'タ', 'tai': 'タイ', 'tan': 'タン', 'tang': 'トウ', 'tao': 'トウ', 'te': 'トク', 'tei': 'テイ', 'teng': 'トウ', 'ti': 'テイ', 'tian': 'テン', 'tiao': 'チョウ', 'tie': 'テツ', 'ting': 'テイ', 'tong': 'トウ', 'tou': 'トウ', 'tu': 'ト', 'tuan': 'タン', 'tui': 'タイ', 'tun': 'トン', 'tuo': 'タ',
    'wa': 'ワ', 'wai': 'ワイ', 'wan': 'ワン', 'wang': 'オウ', 'wei': 'イ', 'wen': 'ブン', 'weng': 'オウ', 'wo': 'ガ', 'wu': 'ム',
    'xi': 'セキ', 'xia': 'カ', 'xian': 'セン', 'xiang': 'ショウ', 'xiao': 'ショウ', 'xie': 'シャ', 'xin': 'シン', 'xing': 'セイ', 'xiong': 'キョウ', 'xiu': 'シュウ', 'xu': 'キョ', 'xuan': 'セン', 'xue': 'ガク', 'xun': 'ジュン',
    'ya': 'ア', 'yan': 'エン', 'yang': 'ヨウ', 'yao': 'ヨウ', 'ye': 'ヤ', 'yi': 'イ', 'yin': 'イン', 'ying': 'エイ', 'yo': 'ヨ', 'yong': 'ヨウ', 'you': 'ユウ', 'yu': 'ギョ', 'yuan': 'エン', 'yue': 'ガツ', 'yun': 'ウン',
    'za': 'ザツ', 'zai': 'ザイ', 'zan': 'サン', 'zang': 'ゾウ', 'zao': 'ソウ', 'ze': 'ソク', 'zei': 'ゾク', 'zen': 'セン', 'zeng': 'ゾウ', 'zha': 'サ', 'zhai': 'サイ', 'zhan': 'セン', 'zhang': 'チョウ', 'zhao': 'チョウ', 'zhe': 'シャ', 'zhen': 'シン', 'zheng': 'セイ', 'zhi': 'シ', 'zhong': 'チュウ', 'zhou': 'チュウ', 'zhu': 'ショ', 'zhua': 'サ', 'zhuai': 'サイ', 'zhuan': 'セン', 'zhuang': 'ソウ', 'zhui': 'ツイ', 'zhun': 'ジュン', 'zhuo': 'タク', 'zi': 'シ', 'zong': 'ソウ', 'zou': 'ソウ', 'zu': 'ソ', 'zuan': 'サン', 'zui': 'サイ', 'zun': 'ソン', 'zuo': 'サク'
  };

  // ピンインの音節を分解
  const syllables = pinyin.match(/[a-zü]+[1-4]?/gi) || [];
  const jpSounds = syllables.map(s => {
    const base = s.replace(/[1-4]/g, '').replace(/ü/g, 'v');
    return syllableMap[base] || s.toUpperCase();
  }).join('');

  const meaning = word.meaning;
  const partsDesc = parts.join('＋');

  return `「${jpSounds}」＝${partsDesc}→「${meaning}」で覚える。`;
}

// 全単語に対して etymology と mnemonic を生成
let addedCount = 0;
const updatedWords = wordsData.map(word => {
  if (word.etymology && word.mnemonic) return word; // 既存はそのまま
  
  return {
    ...word,
    etymology: generateEtymology(word),
    mnemonic: generateMnemonic(word)
  };
});

addedCount = updatedWords.filter(w => w.etymology && w.mnemonic).length;

fs.writeFileSync(wordsPath, JSON.stringify(updatedWords, null, 2));
console.log(`Words done! ${addedCount}/${updatedWords.length} words now have etymology & mnemonic.`);
console.log('All data generation complete!');
